import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";


const StyleFaQ = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.BackGround,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 15,
        marginTop: responsiveScreenHeight(1.5),
    },
    viewcontainer: {
        // height: '100%',
    },
    viewtabcontainer: {
        flexDirection: 'row',
        alignItems: 'center',
        // right: 10,
    },
    viewtab: {
        flexDirection: 'row',
        // marginTop: 29,
        marginTop: responsiveScreenHeight(3),
    },
    tabcontainer: {
        // width: 80,
        // height: 35,
        width: responsiveScreenWidth(20),
        height: responsiveScreenHeight(3.5),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        // marginLeft: 20,
        bottom: responsiveScreenHeight(2),
        marginLeft: responsiveScreenWidth(3),
        justifyContent: 'center',
    },
    activeTab: {
        backgroundColor: Color.MainBlack,
    },
    tabcontainerother: {
        width: responsiveScreenWidth(20),
        height: responsiveScreenHeight(3.5),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        bottom: responsiveScreenHeight(2),
        // marginLeft: 20,
        marginLeft: responsiveScreenWidth(3),
        justifyContent: 'center',
    },
    tabcontainerother1: {
        // width: 110,
        // height: 29,
        width: responsiveScreenWidth(27),
        height: responsiveScreenHeight(3),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        // marginLeft: 20,
        bottom: responsiveScreenHeight(2),
        marginLeft: responsiveScreenWidth(3),
        justifyContent: 'center',
    },
    texttab: {
        // fontSize: 15,
        fontSize: responsiveScreenHeight(1.6),
        fontWeight: '700',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    activeText: {
        color: Color.MainWhite,
        // fontSize: 15,
        fontSize: responsiveScreenHeight(1.6),
        fontWeight: '700',
        textAlign: 'center',
    },
    viewtabcontent: {
        // height: 485,
        // marginHorizontal: 15,
        // marginTop: 15,
        height: responsiveScreenHeight(60),
        marginHorizontal: responsiveScreenWidth(5),
        marginTop: responsiveScreenHeight(3),
        bottom: responsiveScreenHeight(2),
    },
    tabContent: {
        // fontSize: 15,
        fontSize: responsiveScreenHeight(1.6),
        fontWeight: '700',
        color: Color.MainBlack,
    },
    viewsearch: {
        // width: 350,
        // height: 50,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(5.5),
        backgroundColor: Color.MainGray3,
        // marginTop: 10,
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(1),
        marginHorizontal: responsiveScreenWidth(5),
        borderRadius: 15,
    },
    viewsearch1: {
        flexDirection: 'row',
        // marginHorizontal: 20,
        // gap: 5,
        marginHorizontal: responsiveScreenWidth(5),
        gap: responsiveScreenWidth(1),
        alignItems: 'center',
        // top: 2,
        top: responsiveScreenHeight(0.2),
    },
    inputsearch: {
        // fontSize: 16,
        fontSize: responsiveScreenHeight(1.7),
        fontWeight: '700',
        color: Color.MainBlack,
        // width: 300,
        width: responsiveScreenWidth(80),
    },
    iconoption: {
        marginLeft: 'auto',
        color: Color.MainBlack,
    },
    viewtitelsearch: {
        // width: 350,
        // height: 100,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(11),
        backgroundColor: Color.MainWhite,
    },
    viewtitelsearch1: {

    },
    notificationHeader: {
        // marginTop: 15,
        // width: 350,
        marginTop: responsiveScreenHeight(1.5),
        width: responsiveScreenWidth(90),
        backgroundColor: Color.MainWhite,
        borderRadius: 15,
        elevation: 4,
    },
    viewFlast: {
        flexDirection: 'row',
        // marginLeft: 20,
        // top: 10,
        // gap: 5,
        // height: 65,
        marginLeft: responsiveScreenWidth(5),
        top: responsiveScreenHeight(1),
        gap: responsiveScreenWidth(1),
        height: responsiveScreenHeight(7),
    },
    notificationTitle: {
        // fontSize: 15,
        fontSize: responsiveScreenHeight(1.7),
        fontWeight: '700',
        color: Color.MainBlack,
        // top: 10,
        // width: 290,
        top: responsiveScreenHeight(1),
        width: responsiveScreenWidth(75),
    },
    message: {
        // marginLeft: 20,
        // fontSize: 15,
        marginLeft: responsiveScreenWidth(5),
        fontSize: responsiveScreenHeight(1.7),
        color: Color.MainBlack,
        // bottom: 10,
        // marginTop: 15,
        // width: 312,
        bottom: responsiveScreenHeight(1),
        marginTop: responsiveScreenHeight(1.5),
        width: responsiveScreenWidth(73),
        textAlign: 'justify',
        fontWeight: '500',
        lineHeight: responsiveScreenHeight(2.4),
    },
    iconoption: {
        marginLeft: 'auto',
        color: Color.MainBlack,
    },
    iconflast: {
        color: Color.MainBlack,
        marginLeft: 'auto',
        // right: 10,
        // top: 8,
        right: responsiveScreenWidth(2),
        top: responsiveScreenHeight(0.5),
    },
    line: {
        // width: 310,
        // height: 1.5,
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(0.2),
        backgroundColor: Color.MainGray3,
        alignSelf: 'center',
        // bottom: 5,
        // marginTop: 8,
        bottom: responsiveScreenHeight(0.5),
        marginTop: responsiveScreenHeight(0.5),
    },
    line2: {
        // width: 320,
        // height: 1,
        width: responsiveScreenWidth(85),
        height: responsiveScreenHeight(0.1),
        backgroundColor: Color.MainGray2,
        // bottom: 5,
        // top: 8,
        // left: 9,
        bottom: responsiveScreenHeight(0.5),
        top: responsiveScreenHeight(0.5),
        left: responsiveScreenWidth(2.5),
    },
    viewsearch3: {
        // width: 350,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(58),
        backgroundColor: Color.MainWhite,
        borderRadius: 15,
        position: 'absolute',
        // top: '21%',
        top: responsiveScreenHeight(13.5),
        elevation: 5,
        // left: 20,
        left: responsiveScreenWidth(5.5),
    },
    viewsearch2: {
        flexDirection: 'column',
        // gap: 10,
        gap: responsiveScreenHeight(1),
    },
    textsearch: {
        // fontSize: 16,
        fontSize: responsiveScreenHeight(1.75),
        fontWeight: '500',
        color: Color.MainBlack,
        // marginLeft: 10,
        // marginTop: 15,
        marginLeft: responsiveScreenWidth(2.5),
        marginTop: responsiveScreenHeight(1.5),
        textAlign: 'justify',
        // width: 330,
        width: responsiveScreenWidth(80),
    },

});

export default StyleFaQ;