import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenWidth, responsiveScreenFontSize, responsiveScreenHeight } from "react-native-responsive-dimensions";

const styleModalOptionSearch = StyleSheet.create({
    modalContainer: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 60,
        borderTopRightRadius: 60,
        top: responsiveScreenHeight(5.3),
        padding: responsiveScreenWidth(3),
        // height: responsiveScreenHeight(89),
    },
    viewbar: {
        // width: 50,
        width: responsiveScreenWidth(10),
        height: responsiveScreenHeight(0.6),
        backgroundColor: '#ccc',
        borderRadius: 5,
        alignSelf: 'center',
        marginBottom: responsiveScreenHeight(2),
    },
    title: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.4),
        fontWeight: 'bold',
        // marginBottom: 15,
        marginBottom: responsiveScreenHeight(1),
        color: Color.MainBlack,
        textAlign: 'center',
    },
    line: {
        height: 1.5,
        backgroundColor: '#ccc',
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1),
        width: responsiveScreenWidth(87),
        alignSelf: 'center',
    },
    line2: {
        height: 1,
        backgroundColor: '#ccc',
        // width: 330,
        width: responsiveScreenWidth(86),
        alignSelf: 'center',
        bottom: responsiveScreenHeight(0.8),
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    viewcategory: {
        flexDirection: 'row',
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1.2),
        gap: responsiveScreenWidth(2),
        height: responsiveScreenHeight(6.5),
    },
    viewcategorystar: {
        flexDirection: 'row',
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1.3),
        // gap: responsiveScreenWidth(2),
        // height: responsiveScreenHeight(6.5),
    },
    viewcategoryitem: {
        // width: 58,
        // height: 29,
        width: responsiveScreenWidth(13),
        height: responsiveScreenHeight(3),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveScreenWidth(2),
    },
    activeTab: {
        color: Color.MainBlack,
    },
    viewcategoryitem1: {
        // width: 68,
        // height: 29,
        width: responsiveScreenWidth(16),
        height: responsiveScreenHeight(3),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveScreenWidth(2),
    },
    viewcategoryitem2: {
        // width: 105,
        // height: 29,
        width: responsiveScreenWidth(25),
        height: responsiveScreenHeight(3),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveScreenWidth(2),
    },
    viewstar: {
        // width: 70,
        // height: 30,
        width: responsiveScreenWidth(16),
        height: responsiveScreenHeight(3.2),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: responsiveScreenWidth(2),
        flexDirection: 'row',
        gap: responsiveScreenWidth(1),
    },
    textcategory: {
        // marginTop: 19,
        // marginBottom: 5,
        marginTop: responsiveScreenHeight(2.6),
        marginBottom: responsiveScreenHeight(0.8),
        color: Color.MainBlack,
        fontWeight: '600',
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2.1),
        marginLeft: responsiveScreenWidth(2),
    },
    textsortby: {
        // marginTop: 35,
        // marginBottom: 5,
        marginTop: responsiveScreenHeight(4.6),
        marginBottom: responsiveScreenHeight(0.8),
        color: Color.MainBlack,
        fontWeight: '600',
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2.1),
        // marginLeft: 12,
        marginLeft: responsiveScreenWidth(2),
    },
    textcategoryitem: {
        color: Color.MainBlack,
        fontWeight: '600',
        textAlign: 'center',
    },
    textstar: {
        color: Color.MainBlack,
        fontWeight: '600',
        textAlign: 'center',
    },
    viewgender: {
        flexDirection: 'row',
        // marginTop: 10,
        // gap: 15,
        marginTop: responsiveScreenHeight(1.3),
        gap: responsiveScreenWidth(1.3),
    },
    viewfilter: {
        flexDirection: 'column',
        bottom: responsiveScreenHeight(4),
    },
    viewprice: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        marginHorizontal: responsiveScreenWidth(5),
        marginTop: responsiveScreenHeight(1.3),
    },
    textprice: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        // width: 65,
        // height: 30,
        width: responsiveScreenWidth(15.5),
        height: responsiveScreenHeight(4),
        textAlign: 'center',
        borderWidth: 1,
        borderRadius: 9,
        borderColor: Color.MainGray,
        color: Color.MainBlack,
        paddingTop: responsiveScreenHeight(0.6),
    },
    Icon: {
        bottom: responsiveScreenHeight(2),
        color: Color.Black,
    },
    Iconstar: {
        color: Color.MainBlack,
    },
    viewrating: {
        bottom: responsiveScreenHeight(4.5),
    },
    containercheckout: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // marginHorizontal: 10,
        // marginTop: 25,
        marginHorizontal: responsiveScreenWidth(4),
        marginTop: responsiveScreenHeight(3),
    },
    viewcheckout: {
        // width: 150,
        // height: 50,
        width: responsiveScreenWidth(35),
        height: responsiveScreenHeight(5.5),
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Color.MainGray3,
    },
    viewcheckout2: {
        // width: 150,
        // height: 50,
        width: responsiveScreenWidth(35),
        height: responsiveScreenHeight(5.5),
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Color.MainBlack,
    },
    textcheckout: {
        color: Color.MainBlack,
        fontWeight: '500',
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2)
    },
    textcheckout2: {
        color: Color.MainWhite,
        fontWeight: '500',
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2)
    },
});

export default styleModalOptionSearch;