import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveWidth, responsiveFontSize, responsiveHeight } from "react-native-responsive-dimensions";

const styleModalOptionSearch = StyleSheet.create({
    modalContainer: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 60,
        borderTopRightRadius: 60,
        top: responsiveHeight(3),
        padding: responsiveWidth(5),
        height: responsiveHeight(100),
    },
    viewbar: {
        // width: 50,
        width: responsiveWidth(10),
        height: responsiveHeight(0.8),
        backgroundColor: '#ccc',
        borderRadius: 5,
        alignSelf: 'center',
        marginBottom: responsiveHeight(2),
    },
    title: {
        // fontSize: 20,
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        // marginBottom: 15,
        marginBottom: responsiveHeight(2),
        color: Color.MainBlack,
        textAlign: 'center',
    },
    line: {
        height: 1.5,
        backgroundColor: '#ccc',
        // marginTop: 10,
        marginTop: responsiveHeight(1),
        width: responsiveWidth(85),
        alignSelf: 'center',
    },
    line2: {
        height: 1,
        backgroundColor: '#ccc',
        // width: 330,
        width: responsiveWidth(85),
        alignSelf: 'center',
        bottom: responsiveHeight(0.8),
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    viewcategory: {
        flexDirection: 'row',
        // marginTop: 10,
        marginTop: responsiveHeight(1.3),
        gap: responsiveWidth(2),
        height: responsiveHeight(6.5),
    },
    viewcategorystar: {
        flexDirection: 'row',
        // marginTop: 10,
        marginTop: responsiveHeight(1.5),
        gap: responsiveWidth(2),
        height: responsiveHeight(6.5),
    },
    viewcategoryitem: {
        // width: 58,
        // height: 29,
        width: responsiveWidth(13),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveWidth(2),
    },
    activeTab: {
        color: Color.MainBlack,
    },
    viewcategoryitem1: {
        // width: 68,
        // height: 29,
        width: responsiveWidth(16),
        height: responsiveHeight(3.2),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveWidth(2),
    },
    viewcategoryitem2: {
        // width: 105,
        // height: 29,
        width: responsiveWidth(25),
        height: responsiveHeight(3.2),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        marginLeft: responsiveWidth(2),
    },
    viewstar: {
        // width: 70,
        // height: 30,
        width: responsiveWidth(16),
        height: responsiveHeight(3.2),
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: responsiveWidth(2),
        flexDirection: 'row',
        gap: responsiveWidth(1),
    },
    textcategory: {
        // marginTop: 19,
        // marginBottom: 5,
        marginTop: responsiveHeight(2.6),
        marginBottom: responsiveHeight(0.8),
        color: Color.MainBlack,
        fontWeight: '600',
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        marginLeft: responsiveWidth(2),
    },
    textsortby: {
        // marginTop: 35,
        // marginBottom: 5,
        marginTop: responsiveHeight(4.6),
        marginBottom: responsiveHeight(0.8),
        color: Color.MainBlack,
        fontWeight: '600',
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        // marginLeft: 12,
        marginLeft: responsiveWidth(2),
    },
    textcategoryitem: {
        color: Color.MainBlack,
        fontWeight: '600',
        textAlign: 'center',
    },
    textstar: {
        color: Color.MainBlack,
        fontWeight: '600',
        textAlign: 'center',
    },
    viewgender: {
        flexDirection: 'row',
        // marginTop: 10,
        // gap: 15,
        marginTop: responsiveHeight(1.3),
        gap: responsiveWidth(2),
    },
    viewfilter: {
        flexDirection: 'column',
        bottom: responsiveHeight(4),
    },
    viewprice: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        marginHorizontal: responsiveWidth(5),
        marginTop: responsiveHeight(2),
    },
    textprice: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        // width: 65,
        // height: 30,
        width: responsiveWidth(15),
        height: responsiveHeight(4),
        textAlign: 'center',
        borderWidth: 1,
        borderRadius: 5,
        borderColor: Color.MainGray,
        color: Color.MainBlack,
        paddingTop: responsiveHeight(0.5),
    },
    Icon: {
        bottom: responsiveHeight(2),
        color: Color.Black,
    },
    Iconstar: {
        color: Color.MainBlack,
    },
    viewrating: {
        bottom: responsiveHeight(4.5),
    },
    containercheckout: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // marginHorizontal: 10,
        // marginTop: 25,
        marginHorizontal: responsiveWidth(2),
        marginTop: responsiveHeight(3.3),
    },
    viewcheckout: {
        // width: 150,
        // height: 50,
        width: responsiveWidth(35),
        height: responsiveHeight(7),
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Color.MainGray3,
    },
    viewcheckout2: {
        // width: 150,
        // height: 50,
        width: responsiveWidth(35),
        height: responsiveHeight(7),
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Color.MainBlack,
    },
    textcheckout: {
        color: Color.MainBlack,
        fontWeight: '500',
        // fontSize: 16,
        fontSize: responsiveFontSize(2)
    },
    textcheckout2: {
        color: Color.MainWhite,
        fontWeight: '500',
        // fontSize: 16,
        fontSize: responsiveFontSize(2)
    },
});

export default styleModalOptionSearch;