import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { useWindowDimensions, Dimensions } from "react-native";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const { width, height } = Dimensions.get('window');
const widthScreen = width;
const heightScreen = height;

const StyleAccount = StyleSheet.create({
    container: {
        backgroundColor: Color.MainWhite,
        flex: 1,
    },
    header: {
        // backgroundColor: Color.MainWhite,
        marginTop: responsiveScreenHeight(2),
    },
    headerContent: {
        flexDirection: 'row',
        // marginTop: 20,
        // marginTop: responsiveScreenHeight(1.8),
        // marginHorizontal: 20,
        marginHorizontal: responsiveScreenWidth(4),
        alignItems: 'center',
        // gap: 3,
    },
    name: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: '600',
        // marginLeft: 10,
        left: responsiveScreenHeight(1),
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    viewicon: {
        alignItems: 'flex-end',
        // bottom: 28,
        // right: 20,
        bottom: responsiveScreenHeight(2.8),
        right: responsiveScreenHeight(2.2),
    },
    iconname: {
        color: Color.MainBlack,
    },
    viewimage: {
        alignItems: 'center',
        // bottom: 5,
        // right: 5,
        bottom: responsiveScreenHeight(2),
        right: responsiveScreenHeight(1.2),
    },
    viewbuttonimage: {
        alignItems: 'center',
        flexDirection: 'row',
        // marginLeft: 14,
        left: responsiveScreenHeight(2.3),
    },
    image: {
        // width: 120,
        // height: 120,
        width: responsiveScreenHeight(12),
        height: responsiveScreenHeight(12),
        borderRadius: 65,
        // marginLeft: 22,
    },
    iconimage: {
        color: Color.MainBlack,
        // marginTop: 90,
        // right: 32,
        top: responsiveScreenHeight(4.5),
        right: responsiveScreenHeight(3.5),
    },
    imagelogo: {
        // width: 32,
        // height: 32,
        width: responsiveScreenHeight(3.5),
        height: responsiveScreenHeight(3.5),
    },
    textuser: {
        // fontSize: 23,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: '600',
        // marginTop: 6,
        marginTop: responsiveScreenHeight(0.7),
        color: Color.MainBlack,
        letterSpacing: 0.6,
        // marginLeft: 10,
        left: responsiveScreenHeight(1),
    },
    texphone: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: '500',
        // marginTop: 4,
        // marginLeft: 10,
        marginTop: responsiveScreenHeight(0.5),
        left: responsiveScreenHeight(1),
    },
    line: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // width: 350,
        width: responsiveScreenWidth(90),
        alignSelf: 'center',
        marginTop: responsiveScreenHeight(1),
    },
    viewlistitem: {
        // backgroundColor: Color.MainWhite,
        // height: 500,
        // marginBottom: 20,
        height: responsiveScreenHeight(60),
    },
    listItem: {
        // marginTop: 12,
        // marginHorizontal: 22,
        marginTop: responsiveScreenHeight(1.5),
        marginHorizontal: responsiveScreenHeight(2.5),
        flexDirection: 'column',
    },
    item: {
        flexDirection: 'row',
        // height: 43,
        height: responsiveScreenHeight(5.1),
    },
    itemlast: {
        flexDirection: 'row',
        // height: 43,
        // bottom: 5,
        height: responsiveScreenHeight(5.1),
        bottom: responsiveScreenHeight(0.6),
    },
    viewlist: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 15,
        // width: 120,
        width: responsiveScreenHeight(14.3),
        gap: responsiveScreenHeight(2),
    },
    icon: {
        color: Color.MainBlack,
    },
    iconlog: {
        color: Color.MainRed,
    },
    iconright: {
        color: Color.MainBlack,
        left: 256,
        bottom: 2,
    },
    iconrightlanguage: {
        color: Color.MainBlack,
        // left: 256,
        // marginTop: 3,
        left: responsiveScreenHeight(30),
    },
    text: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.95),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    textselectedLanguage: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: '500',
        color: Color.MainBlack,
        // marginLeft: 108,
        left: responsiveScreenHeight(13),
        // width: 95,
        // marginTop: 5,
        width: responsiveScreenHeight(12),
    },
    itemdark: {
        flexDirection: 'row',
        // height: 43,
    },
    viewicondark: {
        // bottom: 25,
        bottom: responsiveScreenHeight(2.5),
        marginLeft: 'auto',
        position: 'relative',
        // width: 38,
        width: responsiveScreenHeight(5.5),
    },
    overlay: {
        position: 'absolute',
        // top: 0,
        // left: 0,
        // right: 0,
        // bottom: 0,
        top: responsiveScreenHeight(0),
        left: responsiveScreenHeight(0),
        right: responsiveScreenHeight(0),
        bottom: responsiveScreenHeight(0),
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        // zIndex: 999,
    },
    viewmodal: {
        backgroundColor: Color.MainWhite,
        width: responsiveScreenWidth(58),
        height: responsiveScreenHeight(30),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        // marginTop: '70%',
        top: responsiveScreenHeight(27),
        elevation: 6,
        // gap: 20,
        gap: responsiveScreenHeight(2),
    },
    texttitle: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '600',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // bottom: 10,
    },
    viewmodalcontainer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        // gap: 20,
        gap: responsiveScreenHeight(2),
    },
    texttitlelogout: {
        // fontSize: 19,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: '600',
        color: Color.MainRed,
        letterSpacing: 0.25,
    },
    textchoose: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        fontWeight: '700',
        color: Color.MainBlack,
    },
    viewbutton: {
        flexDirection: 'row',
        // gap: 28,
        // marginTop: 10,
        gap: responsiveScreenHeight(3.3),
        top: responsiveScreenHeight(1.5),
    },
    viewcancel: {
        // width: 135,
        // height: 40,
        width: responsiveScreenHeight(15.8),
        height: responsiveScreenHeight(4.7),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Color.MainGray3,
        elevation: 5,
    },
    textcancel: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewlogout: {
        // width: 135,
        // height: 40,
        width: responsiveScreenHeight(15.8),
        height: responsiveScreenHeight(4.7),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Color.MainBlack,
        elevation: 5,
    },
    textlogout: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: '500',
        color: Color.MainWhite,
    },
});

export default StyleAccount;