import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveWidth, responsiveFontSize, responsiveHeight } from "react-native-responsive-dimensions";


const StyleHomShoes = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: responsiveHeight(1),
        marginHorizontal: 10,
    },
    headerboder: {
        marginTop: responsiveHeight(1),
        marginLeft: responsiveWidth(4),
    },
    headerTitle: {
        marginLeft: responsiveWidth(2),
        flexDirection: 'column',
    },
    headerTitleText: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainGray2,
        letterSpacing: 0.5,
        marginTop: responsiveHeight(0.5),
    },
    headertext: {
        // fontSize: 19,
        fontSize: responsiveFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    viewicon: {
        flexDirection: 'row',
        // marginLeft: 80,
        marginLeft: responsiveWidth(14),
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: responsiveWidth(2),
    },
    notificationCount: {
        width: responsiveWidth(5),
        height: responsiveHeight(2.5),
        borderRadius: 15,
        backgroundColor: Color.MainRed,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: responsiveHeight(0.7),
        left: responsiveWidth(5),
    },
    notificationCountText: {
        color: Color.MainWhite,
    },
    headerinput: {
        flexDirection: 'row',
        backgroundColor: Color.BackGround,
        width: responsiveWidth(90),
        height: responsiveHeight(6.5),
        borderRadius: 15,
        marginTop: responsiveHeight(2.5),
        alignSelf: 'center',
    },
    textinput: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        marginLeft: responsiveWidth(3),
        marginTop: responsiveHeight(0.5),
        width: responsiveWidth(75),
    },
    viewtextheader: {
        flexDirection: 'row',
        marginTop: responsiveHeight(3),
        justifyContent: 'space-between',
        marginHorizontal: responsiveWidth(6),
    },
    viewtitlecategory: {
        flexDirection: 'row',
        marginTop: responsiveHeight(3),
        justifyContent: 'space-between',
        right: responsiveWidth(2),
    },
    textheader: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewimage: {
        marginTop: responsiveHeight(2.5),
        marginVertical: responsiveHeight(1.5),
    },
    imageContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: responsiveWidth(11),
        paddingHorizontal: responsiveWidth(5),
    },
    image: {
        width: responsiveWidth(90),
        height: responsiveHeight(19.5),
        borderRadius: 18,
        alignSelf: 'center',
        borderColor: 'red',
        borderWidth: 2,
        resizeMode: 'center',
    },
    viewcontainercatogory: {
        flexDirection: 'column',
        alignSelf: 'center',
        gap: responsiveHeight(5),
    },
    viewcategorty1: {
        flexDirection: 'row',
        marginTop: responsiveHeight(1),
        gap: responsiveWidth(8),
        left: responsiveWidth(0.5),
    },
    viewcategorty2: {
        flexDirection: 'row',
        marginTop: responsiveHeight(1),
        gap: responsiveWidth(8),
        left: responsiveWidth(0.5),
    },
    categoryimage: {
        backgroundColor: Color.White,
        // height: 60,
        // width: 60,
        width: responsiveWidth(15),
        height: responsiveHeight(8),
        borderRadius: 35,
    },
    imagecategory: {
        // width: 40,
        // height: 40,
        width: responsiveWidth(8),
        height: responsiveHeight(5),
        alignSelf: 'center',
        marginTop: responsiveHeight(1.8)
    },
    imagecategorybalance: {
        width: responsiveWidth(10),
        height: responsiveHeight(3),
        alignSelf: 'center',
        marginTop: responsiveHeight(2.5),
    },
    imagecategoryconverse: {
        width: responsiveWidth(8),
        height: responsiveHeight(3),
        alignSelf: 'center',
        marginTop: responsiveHeight(2.5),
    },
    textcategory: {
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginLeft: 12,
        // marginTop: 18,
        // width: 80,
        marginLeft: responsiveWidth(2),
        marginTop: responsiveHeight(2.3),
    },
    textcategorywidth: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginLeft: 5,
        // marginTop: 18,
        // width: 80,
        marginLeft: responsiveWidth(1),
        marginTop: responsiveHeight(2.3),
        width: responsiveWidth(14),
    },
    textcategoryreebok: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginLeft: 2,
        // marginTop: 21,
        // width: 80,
        marginTop: responsiveHeight(2.6),
        width: responsiveWidth(15),
    },
    textcategorybalance: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginLeft: 2,
        // marginTop: 30,
        // width: 80,
        marginTop: responsiveHeight(3.9),
        width: responsiveWidth(25),
    },
    textcategoryconverse: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginTop: 30,
        // marginLeft: -2,
        // width: 80,
        right: responsiveWidth(1.5),
        marginTop: responsiveHeight(3.9),
        width: responsiveWidth(19),
    },
    textcategorybalanciga: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.5,
        // marginTop: 30,
        // marginLeft: -2,
        // width: 80,
        marginTop: responsiveHeight(2.6),
        width: responsiveWidth(23),
    },
    viewtabcontainer: {
        flexDirection: 'row',
    },
    viewtab: {
        flexDirection: 'row',
        marginTop: responsiveHeight(4.5),
    },
    tabcontainer: {
        // width: 58,
        // height: 29,
        width: responsiveWidth(15),
        height: responsiveHeight(4),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        // marginLeft: 20,
        bottom: responsiveHeight(2.5),
        marginLeft: responsiveWidth(6),
        justifyContent: 'center',
    },
    activeTab: {
        backgroundColor: "black",
    },
    tabcontainerother: {
        // width: 72,
        // height: 29,
        width: responsiveWidth(18),
        height: responsiveHeight(4),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        // marginLeft: 20,
        bottom: responsiveHeight(2.5),
        marginLeft: responsiveWidth(4),
        justifyContent: 'center',
    },
    tabcontainerother1: {
        // width: 110,
        // height: 29,
        width: responsiveWidth(27),
        height: responsiveHeight(4),
        borderWidth: 2,
        borderRadius: 15,
        // bottom: 19,
        // marginLeft: 20,
        bottom: responsiveHeight(2.5),
        marginLeft: responsiveWidth(4),
        justifyContent: 'center',
    },
    texttab: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    activeText: {
        color: Color.MainWhite,
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        textAlign: 'center',
    },
    viewitemtab: {

    },
    viewtabcontent: {
        // marginHorizontal: 20,
        marginHorizontal: responsiveWidth(4),
        // height: 11500,
        height: '100%',
        // backgroundColor: Color.MainWhite,
    },
    viewflash: {
        flex: 1,
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        //  marginHorizontal: 10,
        alignItems: 'center',
        marginBottom: responsiveHeight(2.3),
        gap: responsiveHeight(1.5),
    },
    viewbackground: {
        flexDirection: 'row',
        // backgroundColor: Color.Gray,
        // width: 160,
        // height: 150,
        width: responsiveWidth(40),
        height: responsiveHeight(20),
        borderRadius: 28,
        justifyContent: 'center',
        // elevation: 3,
    },
    viewitemimage: {
        left: responsiveWidth(3),
    },
    imageItem: {
        // width: 135,
        // height: 135,
        width: responsiveWidth(33),
        height: responsiveHeight(17),
        // top: 15,
        top: responsiveHeight(2),
    },
    viewiconheart: {
        backgroundColor: Color.MainBlack,
        // height: 28,
        // width: 28,
        height: responsiveHeight(3.8),
        width: responsiveWidth(7.2),
        borderRadius: 38,
        top: responsiveHeight(1.7),
        right: responsiveWidth(4),
    },
    iconheart: {
        top: responsiveHeight(0.5),
        left: responsiveWidth(1),
    },
    tabContent: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
    },
    textname: {
        color: Color.MainBlack,
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        // width: 145,
        width: responsiveWidth(40),
        letterSpacing: 0.25,
        // left: 8,
        // top: 5,
        left: responsiveWidth(1.8),
        top: responsiveHeight(0.5),
    },
    texprice: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        // width: 145,
        width: responsiveWidth(36),
        letterSpacing: 0.25,
    },
    ratingContainer: {
        flexDirection: 'row',
        // gap: 10,
        // right: 2,
        gap: responsiveWidth(2),
        right: responsiveWidth(0.5),
    },
    viewrating: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: responsiveWidth(1),
    },
    starIcon: {
        color: Color.Black,
    },
    ratingText: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
    },
    viewline: {
        // width: 2,
        // height: 15,
        width: responsiveWidth(0.5),
        height: responsiveHeight(2.5),
        backgroundColor: Color.MainGray,
        top: responsiveHeight(0.5),
    },
    viewsold: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        // gap: 5,
        // width: 80,
        // height: 22,
        width: responsiveWidth(20),
        height: responsiveHeight(3),
        backgroundColor: Color.MainGray3,
        borderRadius: 6,
        top: 2,
    },
    viewCountText: {
        color: Color.MainBlack,
        // fontSize: 11,
        fontSize: responsiveFontSize(1.5),
        fontWeight: '500',
    },
    imageAvatar: {
        // width: 55,
        // height: 55,
        width: responsiveWidth(15),
        height: responsiveHeight(7.8),
        borderRadius: 55,
    },
    favoriteCount: {
        // width: 18,
        // height: 18,
        width: responsiveWidth(5),
        height: responsiveHeight(2.8),
        borderRadius: 15,
        backgroundColor: Color.MainRed,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        // top: 5,
        // left: 20,
        top: responsiveHeight(0.5),
        left: responsiveWidth(6),
    },
    favoriteCountText: {
        color: Color.MainWhite,
        // fontSize: 12,
        fontSize: responsiveFontSize(1.8),
        fontWeight: 'bold',
    },
});

export default StyleHomShoes;