import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";


const StyleOrderActive = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    containerItem: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    containerCartItem: {
        // width: '90%',
        // height: 118,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(12),
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Color.MainWhite,
        elevation: 5,
        borderRadius: 15,
        alignSelf: 'center',
        // marginTop: 25,
        // gap: 15,
        marginTop: responsiveScreenHeight(3),
        gap: responsiveScreenHeight(2),
    },
    viewheader: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
        bottom: responsiveScreenHeight(5),
    },
    image: {
        // width: 200,
        // height: 200,
        width: responsiveScreenHeight(23),
        height: responsiveScreenHeight(23),
        resizeMode: 'contain',
    },
    viewtext: {
        justifyContent: 'center',
        alignItems: 'center',
        // marginTop: 20,
        // gap: 8,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(1),
    },
    text: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    text1: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
    },
    viewImageCartItem: {
        // width: 100,
        // height: 100,
        width: responsiveScreenHeight(9.8),
        height: responsiveScreenHeight(9.8),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        marginLeft: responsiveScreenHeight(1.8),
    },
    imageCartItem: {
        // width: 90,
        // height: 90,
        width: responsiveScreenHeight(8),
        height: responsiveScreenHeight(8),
        resizeMode: 'contain',
    },
    viewTextCartItem: {
        flexDirection: 'column',
        // gap: 5,
        gap: responsiveScreenHeight(0.4),
    },
    textCartItemname: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    textCartItemqty: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.5),
        color: Color.MainGray,
        fontWeight: '400',
        letterSpacing: 0.7,
    },
    textCartItemdelivery: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.4),
        color: Color.MainBlack,
        fontWeight: '500',
        // width: 79,
        // height: 20,
        width: responsiveScreenHeight(9),
        height: responsiveScreenHeight(2.2),
        backgroundColor: Color.MainGray3,
        borderRadius: 5,
        textAlign: 'center',
        top: responsiveScreenHeight(0.3),
    },
    viewTextCartItemprice: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // width: 200,
        width: responsiveScreenHeight(26),
    },
    textCartItemprice: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    textCartItemtrack: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.5),
        color: Color.MainWhite,
        fontWeight: '500',
        // width: 90,
        // height: 33,
        width: responsiveScreenHeight(10.5),
        height: responsiveScreenHeight(3),
        backgroundColor: Color.MainBlack,
        borderRadius: 18,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
});


export default StyleOrderActive;