import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StyleSmsOtp = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    viewbody: {
        // marginTop: 10,
        // marginTop: responsiveScreenHeight(0.5),
    },
    viewlogo: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 20,
        // marginHorizontal: 20,
        // gap: 10,
        marginTop: responsiveScreenHeight(1),
        left: responsiveScreenWidth(2),
        gap: responsiveScreenWidth(2),
    },
    iconback: {
        color: Color.MainBlack,
    },
    textlogo: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        bottom: responsiveScreenHeight(0.1),
    },
    viewotp: {
        // marginTop: 20,
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(2),
        marginHorizontal: responsiveScreenWidth(4),
        flexDirection: 'row',
        alignSelf: 'center',
        // gap: 12,
        gap: responsiveScreenWidth(4),
    },
    viewtext: {
        // marginTop: '45%',
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(20),
        alignSelf: 'center',
        right: responsiveScreenWidth(1.5),
    },
    text: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.MainBlack,
        fontWeight: '500',
        textAlign: 'center',
    },
    input: {
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 12,
        // paddingHorizontal: 16,
        // paddingVertical: 12,
        // marginHorizontal: 4,
        paddingHorizontal: responsiveScreenWidth(4),
        paddingVertical: responsiveScreenHeight(1.5),
        marginHorizontal: responsiveScreenWidth(1),
        textAlign: 'center',
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        // top: 20,
        top: responsiveScreenHeight(2),
    },
    viewsend: {
        // marginTop: 70,
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(8),
        marginHorizontal: responsiveScreenWidth(4),
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        // gap: 5,
        gap: responsiveScreenWidth(1),
    },
    viewverify: {
        // marginTop: 20,
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(2),
        alignSelf: 'center',
        backgroundColor: Color.MainBlack,
        borderRadius: 35,
        // width: 300,
        // height: 50,
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(6),
        justifyContent: 'center',
        elevation: 6,
    },
    textverify: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        color: Color.MainWhite,
        fontWeight: '500',
        textAlign: 'center',
    },
    negative: {
        color: 'red',
    },
});

export default StyleSmsOtp;