import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StylePayment = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    body: {
        backgroundColor: Color.MainWhite,
        // marginTop: 30,
        // gap: 20,
        marginTop: responsiveScreenHeight(1.5),
        gap: responsiveScreenHeight(1.5),
    },
    viewheader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    titleheader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 8,
        // top: 1,
        marginLeft: responsiveScreenWidth(2),
        top: responsiveScreenHeight(0.1),
        color: Color.MainBlack,
    },
    textheader: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        // marginLeft: 14,
        left: responsiveScreenWidth(3),
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    viewPaymentIcon: {
        marginLeft: 'auto',
        // marginRight: 20,
        right: responsiveScreenWidth(4),
    },
    viewPaymentmethod: {
        alignItems: 'center',
        justifyContent: 'center',
        // marginTop: 25,
        // gap: 30,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(2),
    },
    choosepayment: {
        flexDirection: 'row',
        // width: 350,
        // height: 60,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(5.8),
        backgroundColor: Color.BackGround,
        borderRadius: 10,
        alignItems: 'center',
        elevation: 2,
    },
    choosepaymentgg: {
        flexDirection: 'row',
        // width: 350,
        // height: 50,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(5.2),
        backgroundColor: Color.MainGray3,
        borderRadius: 10,
        alignItems: 'center',
    },
    imagepayment: {
        // width: 28,
        // height: 28,
        width: responsiveScreenWidth(6.5),
        height: responsiveScreenHeight(3),
        // marginLeft: 20,
        // top: 1,
        marginLeft: responsiveScreenWidth(4),
    },
    imagemaster: {
        // width: 48,
        // height: 28,
        width: responsiveScreenWidth(11),
        height: responsiveScreenHeight(3),
        // marginLeft: 10,
        // top: 2,
        marginLeft: responsiveScreenWidth(2),
        top: responsiveScreenHeight(0.2),
        resizeMode: 'contain',
    },
    textpayment: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        // marginLeft: 14,
        left: responsiveScreenWidth(3),
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    textmaster: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: '500',
        // marginLeft: 6,
        left: responsiveScreenWidth(1.5),
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    buttonconnect: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveScreenWidth(4),
    },
    textconnect: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.5,
    },
    buttonadd: {
        // width: 350,
        // height: 60,
        width: responsiveScreenWidth(88),
        height: responsiveScreenHeight(5.9),
        backgroundColor: Color.MainBlack,
        borderRadius: 29,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        elevation: 6,
        marginTop: responsiveScreenHeight(40),
    },
    textadd: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Color.MainWhite,
        letterSpacing: 0.25,
    },
});


export default StylePayment;