import { StyleSheet } from "react-native";
import { Color } from "../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StyleNewsPassWord = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    viewbody: {
        // marginTop: 10,
        marginTop: responsiveScreenHeight(0.5),
    },
    viewlogo: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 20,
        // marginHorizontal: 20,
        // gap: 10,
        marginTop: responsiveScreenHeight(0.9),
        left: responsiveScreenWidth(2),
        gap: responsiveScreenWidth(2),
    },
    iconback: {
        color: Color.MainBlack,
    },
    textlogo: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // bottom: 1,
        bottom: responsiveScreenHeight(0.1),
    },
    image: {
        // width: 380,
        // height: 298,
        width: responsiveScreenWidth(83),
        height: responsiveScreenHeight(30),
        alignSelf: 'center',
        // marginTop: 50,
        marginTop: responsiveScreenHeight(6),
    },
    viewpassword: {
        // marginTop: '10%',
        // marginHorizontal: 20,
        marginTop: responsiveScreenHeight(4),
        marginHorizontal: responsiveScreenWidth(4),
        gap: responsiveScreenWidth(1.5),
    },
    text: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // marginBottom: 25,
        marginBottom: responsiveScreenHeight(2.5),
    },
    viewinput1: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginBottom: 17,
        // width: '100%',
        // height: 50,
        marginBottom: responsiveScreenHeight(1.7),
        width: responsiveScreenWidth(92),
        height: responsiveScreenHeight(5.8),
        borderRadius: 18,
        backgroundColor: Color.White,
    },
    viewinput2: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginBottom: 10,
        // width: '100%',
        // height: 50,
        marginBottom: responsiveScreenHeight(1),
        width: responsiveScreenWidth(92),
        height: responsiveScreenHeight(5.8),
        borderRadius: 18,
        backgroundColor: Color.White,
    },
    icon: {
        color: Color.MainBlack,
        // marginHorizontal: 10,
        marginLeft: responsiveScreenWidth(3.5),
    },
    viewiconpassword: {
        // right: 10,
        right: responsiveScreenWidth(2.8),
        justifyContent: 'flex-end',
        position: 'absolute',
    },
    iconpassword: {
        color: Color.MainBlack,
    },
    input: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: '500',
        left: responsiveScreenWidth(1.8),
    },
    button: {
        // width: '100%',
        // height: 55,
        width: responsiveScreenWidth(89),
        height: responsiveScreenHeight(6),
        borderRadius: 38,
        backgroundColor: Color.MainBlack,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        // marginTop: 10,
        marginTop: responsiveScreenHeight(7.5),
        elevation: 6,
    },
    textbutton: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.1),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    textcheckbox: {
        color: Color.MainBlack,
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
    },
    checkbox: {
        borderWidth: 0,
        alignSelf: 'center',
        // marginRight: 10,
    },
});

export default StyleNewsPassWord;