import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenWidth, responsiveScreenFontSize, responsiveScreenHeight } from "react-native-responsive-dimensions";


const StyleWhistList = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveScreenHeight(1.8),
    },
    headerbar: {
        flexDirection: "row",
        alignItems: "center",
    },
    iconback: {
        // marginLeft: 18,
        marginLeft: responsiveScreenWidth(2),
    },
    title: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: "bold",
        // marginLeft: 15,
        left: responsiveScreenWidth(2),
        color: Color.MainBlack,
    },
    iconsearch: {
        marginLeft: 'auto',
        // marginRight: 20,
        right: responsiveScreenWidth(3),
    },
    viewflashlit: {
        // width: '100%',
        // height: '100%',
        // marginTop: 40,
    },
    viewbody: {
        // marginTop: 20,
        marginTop: responsiveScreenHeight(2),
        // marginHorizontal: 20,
        marginHorizontal: responsiveScreenWidth(2),
        // width: '100%',
        alignSelf: 'center',
    },
    viewtab: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // marginBottom: 10,
        // gap: 15,
        // marginLeft: 10,
        gap: responsiveScreenWidth(3.5),
        marginLeft: responsiveScreenWidth(2),
    },
    tabcontainer: {
        // width: 60,
        // height: 30,
        width: responsiveScreenWidth(15.8),
        height: responsiveScreenHeight(3.3),
        borderWidth: 2,
        borderRadius: 15,
        borderColor: Color.MainBlack,
    },
    tabcontainerother: {
        // width: 79,
        // height: 30,
        width: responsiveScreenWidth(20),
        height: responsiveScreenHeight(3.3),
        borderWidth: 2,
        borderRadius: 15,
        borderColor: Color.MainBlack,
    },
    tabcontainerother1: {
        // width: 110,
        // height: 30,
        width: responsiveScreenWidth(26.5),
        height: responsiveScreenHeight(3.3),
        borderWidth: 2,
        borderRadius: 15,
        borderColor: Color.MainBlack,
    },
    texttab: {
        textAlign: 'center',
        // paddingVertical: 2,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        paddingVertical: responsiveScreenHeight(0.2),
        fontWeight: '600',
        color: Color.MainBlack,
    },
    activeTab: {
        backgroundColor: Color.MainBlack,
    },
    activeText: {
        color: Color.MainWhite,
    },
    viewactivetab: {
    },
    viewtabcontent: {
        flexDirection: 'row',
        // marginTop: 20,
        // width: '100%',
        // height: '100%',
        marginTop: responsiveScreenHeight(2),
        width: responsiveScreenWidth(100),
        height: responsiveScreenHeight(100),
    },
    viewflash: {
        flex: 1,
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        // marginBottom: 20,
        // gap: 10,
        marginHorizontal: responsiveScreenWidth(7),
        marginBottom: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(1),
    },
    viewbackground: {
        flexDirection: 'row',
        backgroundColor: Color.Gray,
        // width: 160,
        // height: 150,
        width: responsiveScreenWidth(36),
        height: responsiveScreenHeight(15),
        borderRadius: 28,
        justifyContent: 'center',
    },
    viewitemimage: {
        marginLeft: 25,
    },
    imageItem: {
        // width: 150,
        // height: 150,
        width: responsiveScreenWidth(25),
        height: responsiveScreenHeight(15),
        top: responsiveScreenHeight(1.5),
    },
    viewiconheart: {
        backgroundColor: Color.MainBlack,
        // height: 28,
        // width: 28,
        height: responsiveScreenHeight(3.3),
        width: responsiveScreenWidth(7),
        borderRadius: 35,
        // marginTop: 20,
        // right: 35,
        marginTop: responsiveScreenHeight(1.5),
        right: responsiveScreenWidth(5),
    },
    iconheart: {
        // marginTop: 4,
        // marginLeft: 4,
        marginTop: responsiveScreenHeight(0.5),
        marginLeft: responsiveScreenWidth(1),
    },
    textname: {
        color: Color.MainBlack,
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        // width: 145,
        // letterSpacing: 0.25,
        // top: 5,
        // left: 7
        width: responsiveScreenWidth(37),
        letterSpacing: 0.25,
        top: responsiveScreenHeight(0.5),
        left: responsiveScreenWidth(1),
    },
    texprice: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        // width: 145,
        width: responsiveScreenWidth(37),
        letterSpacing: 0.25,
    },
    ratingContainer: {
        flexDirection: 'row',
        // gap: 10,
        // right: 2,
        gap: responsiveScreenWidth(2.5),
        right: responsiveScreenWidth(0.5),
    },
    viewrating: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        // gap: 5,
        gap: responsiveScreenWidth(1.5),
    },
    starIcon: {
        color: Color.Black,
    },
    ratingText: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: '500',
    },
    viewline: {
        // width: 2,
        // height: 15,
        width: responsiveScreenWidth(0.5),
        height: responsiveScreenHeight(1.7),
        backgroundColor: Color.MainGray,
        // marginTop: 5,
        top: responsiveScreenHeight(0.5),
    },
    viewsold: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        // gap: 5,
        // width: 80,
        // height: 22,
        gap: responsiveScreenWidth(1.5),
        width: responsiveScreenWidth(18),
        height: responsiveScreenHeight(2.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 6,
        // top: 2,
        top: responsiveScreenHeight(0.2),
    },
    viewCountText: {
        color: Color.MainBlack,
        // fontSize: 11,
        fontSize: responsiveScreenFontSize(1.4),
        fontWeight: '500',
    },
});

export default StyleWhistList;