import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveFontSize, responsiveHeight, responsiveWidth } from "react-native-responsive-dimensions";

const StyleTransactionHistory = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        marginTop: responsiveHeight(2),
    },
    iconleft: {
        // marginLeft: 15,
        // top: 2,
        marginLeft: responsiveHeight(1.3),
        top: responsiveHeight(0.2),
    },
    textheader: {
        // fontSize: 21,
        fontSize: responsiveFontSize(2.7),
        fontWeight: 'bold',
        color: Color.MainBlack,
        left: responsiveHeight(1),
    },
    iconsearh: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveHeight(1.5),
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // width: '93%',
        // height: 40,
        width: responsiveWidth(90),
        height: responsiveHeight(5.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 25,
        alignSelf: 'center',
        marginTop: responsiveHeight(2),
    },
    searchIcon: {
        // marginLeft: 14,
        marginLeft: responsiveHeight(1.8),
    },
    searchInput: {
        // width: '90%',
        // height: '100%',
        width: responsiveWidth(80),
        height: responsiveHeight(5.5),
        // fontSize: 13,
        fontSize: responsiveFontSize(1.7),
        letterSpacing: 0.25,
        // left: 5,
        left: responsiveHeight(0.6),
    },
    viewlist: {
        // marginTop: 20,
        // marginHorizontal: 24,
        marginTop: responsiveHeight(2),
        marginHorizontal: responsiveHeight(2.5),
        // width: '90%',
        // height: '100%',
        width: responsiveWidth(90),
        height: responsiveHeight(100),
    },
    viewitem: {
        flexDirection: 'column',
        // gap: 10,
        // marginBottom: 15,
        // marginTop: 15,
        marginTop: responsiveHeight(2),
        marginBottom: responsiveHeight(1.5),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 10,
        gap: responsiveHeight(1.5),
    },
    viewimage: {
        // width: 63,
        // height: 60,
        width: responsiveHeight(8),
        height: responsiveHeight(7.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        // width: 65,
        // height: 65,
        width: responsiveHeight(7.5),
        height: responsiveHeight(7.5),
    },
    viewtext: {
        flexDirection: 'column',
        // width: '75%',
        width: responsiveWidth(69.5),
    },
    viewname: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // bottom: 7,
        bottom: responsiveHeight(0.8),
    },
    textname: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textprice: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewtime: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // top: 2,
        top: responsiveHeight(0.2),
    },
    texttime: {
        // fontSize: 13.5,
        fontSize: responsiveFontSize(1.7),
        fontWeight: '400',
        color: Color.MainBlack,
        letterSpacing: 0.25
    },
    viewicon: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewiconup: {
        // width: 21,
        // height: 21,
        width: responsiveHeight(2.5),
        height: responsiveHeight(2.5),
        backgroundColor: Color.MainRed,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 2,
        left: 8,
    },
});


export default StyleTransactionHistory;