import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StyleTransactionHistory = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        marginTop: responsiveScreenHeight(1.8),
    },
    iconleft: {
        // marginLeft: 15,
        // top: 2,
        marginLeft: responsiveScreenHeight(1.3),
        top: responsiveScreenHeight(0.2),
    },
    textheader: {
        // fontSize: 21,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        left: responsiveScreenHeight(1),
    },
    iconsearh: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveScreenHeight(1.5),
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // width: '93%',
        // height: 40,
        width: responsiveScreenWidth(85),
        height: responsiveScreenHeight(5),
        backgroundColor: Color.MainGray3,
        borderRadius: 25,
        alignSelf: 'center',
        marginTop: responsiveScreenHeight(2),
    },
    searchIcon: {
        // marginLeft: 14,
        marginLeft: responsiveScreenHeight(4),
    },
    searchInput: {
        // width: '90%',
        // height: '100%',
        width: responsiveScreenWidth(80),
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.6),
        letterSpacing: 0.25,
        // left: 5,
        left: responsiveScreenHeight(0.6),
    },
    viewlist: {
        // marginTop: 20,
        // marginHorizontal: 24,
        marginTop: responsiveScreenHeight(1),
        marginHorizontal: responsiveScreenHeight(2.5),
        // width: '90%',
        // height: '100%',
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(100),
    },
    viewitem: {
        flexDirection: 'column',
        // gap: 10,
        // marginBottom: 15,
        // marginTop: 15,
        marginTop: responsiveScreenHeight(2),
        marginBottom: responsiveScreenHeight(1),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 10,
        gap: responsiveScreenHeight(1.5),
    },
    viewimage: {
        // width: 63,
        // height: 60,
        width: responsiveScreenHeight(7),
        height: responsiveScreenHeight(6.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        // width: 65,
        // height: 65,
        width: responsiveScreenHeight(6.8),
        height: responsiveScreenHeight(6.8),
    },
    viewtext: {
        flexDirection: 'column',
        // width: '75%',
        width: responsiveScreenWidth(69.5),
    },
    viewname: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // bottom: 7,
        bottom: responsiveScreenHeight(0.8),
    },
    textname: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textprice: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewtime: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // top: 2,
        top: responsiveScreenHeight(0.2),
    },
    texttime: {
        // fontSize: 13.5,
        fontSize: responsiveScreenFontSize(1.6),
        fontWeight: '400',
        color: Color.MainBlack,
        letterSpacing: 0.25
    },
    viewicon: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewiconup: {
        // width: 21,
        // height: 21,
        width: responsiveScreenHeight(2.3),
        height: responsiveScreenHeight(2.3),
        backgroundColor: Color.MainRed,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        // marginLeft: 2,
        // left: 8,
        marginLeft: responsiveScreenHeight(0.2),
        left: responsiveScreenHeight(0.8),
    },
});


export default StyleTransactionHistory;