import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveWidth, responsiveFontSize, responsiveHeight } from "react-native-responsive-dimensions";


const StylePaymentMethod = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveHeight(3),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 10,
        // marginTop: 2,
        marginLeft: responsiveWidth(2),
        marginTop: responsiveHeight(0.5),
    },
    title: {
        // fontSize: 20,
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        left: responsiveWidth(3),
        color: Color.MainBlack,
    },
    iconother: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveWidth(3),
    },
    textseclect: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        justifyContent: 'center',
        // marginLeft: 20,
        // marginTop: 22,
        marginLeft: responsiveWidth(5),
        marginTop: responsiveHeight(3),
        color: Color.MainGray,
    },
    viewpayment: {
        // marginTop: 10,
        marginTop: responsiveHeight(1),
    },
    viewpaymentlist: {
        alignItems: 'center',
        flexDirection: 'column',
        // marginTop: 15,
        marginTop: responsiveHeight(2),
        gap: responsiveHeight(2.8),
    },
    listchoosepayment: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '95%',
        // height: 60,
        width: responsiveWidth(93),
        height: responsiveHeight(8),
        backgroundColor: Color.MainWhite,
        elevation: 5,
        borderRadius: 13,
    },
    paymentmastercard: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '95%',
        // height: 60,
        width: responsiveWidth(93),
        height: responsiveHeight(8),
        backgroundColor: Color.MainWhite,
        elevation: 5,
        borderRadius: 13,
    },
    imagepaypal: {
        // marginLeft: 20,
        // width: 30,
        // height: 30,
        marginLeft: responsiveWidth(5),
        width: responsiveWidth(7),
        height: responsiveWidth(7),
    },
    imagegoogle: {
        // marginLeft: 20,
        // width: 45,
        // height: 45,
        marginLeft: responsiveWidth(5),
        width: responsiveWidth(10),
        height: responsiveWidth(10),
    },
    imagemastercard: {
        // marginLeft: 20,
        // width: 39,
        // height: 30,
        marginLeft: responsiveWidth(5),
        width: responsiveWidth(9),
        height: responsiveWidth(7),
    },
    textpayment: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        // marginLeft: 20,
        marginLeft: responsiveWidth(5),
        color: Color.MainBlack,
    },
    viewconfirm: {
        flex: 1,
        justifyContent: 'flex-end',
        // marginBottom: 20,
        marginBottom: responsiveHeight(2),
    },
    buttonconfirm: {
        backgroundColor: Color.MainBlack,
        // height: 50,
        height: responsiveHeight(7),
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        // marginHorizontal: 20,
        marginHorizontal: responsiveWidth(5),
        elevation: 5,
    },
    textconfirm: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    modalBackground: {
        flex: 1,
        backgroundColor: 'rgba(0, 5, 10, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 38,
        // width: '75%',
        // height: 418,
        width: responsiveWidth(75),
        height: responsiveHeight(58),
    },
    viewiconorder: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // marginTop: 20,
        // width: '18%',
        // height: 50,
        marginTop: responsiveHeight(2.3),
        width: responsiveWidth(15),
        height: responsiveHeight(7),
        backgroundColor: Color.MainBlack,
        borderRadius: 40,
        position: 'absolute',
        // top: '14%',
        // right: '40%',
        top: responsiveHeight(7.5),
        right: responsiveWidth(30),
    },
    imageorder: {
        // width: 160,
        // height: 160,
        // marginTop: 20,
        width: responsiveWidth(40),
        height: responsiveWidth(40),
        marginTop: responsiveHeight(2.3),
        alignSelf: 'center',
    },
    iconorder: {
        // right: 3,
    },
    textorder: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        textAlign: 'center',
        // marginTop: 20,
        marginTop: responsiveHeight(2.3),
    },
    viewordercheckout: {
        flexDirection: 'column',
        alignItems: 'center',
        // marginTop: 10,
        marginTop: responsiveHeight(1),
    },
    textmadorder: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainGray,
    },
    viewbutoonorder: {
        flexDirection: 'column',
        alignItems: 'center',
        // marginTop: 23,
        marginTop: responsiveHeight(3.8),
        gap: responsiveHeight(2.5),
    },
    buttonorder1: {
        backgroundColor: Color.MainBlack,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        // width: 250,
        // height: 50,
        width: responsiveWidth(65),
        height: responsiveHeight(6.5),
    },
    buttonorder2: {
        backgroundColor: Color.MainGray3,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        // width: 250,
        // height: 50,
        width: responsiveWidth(65),
        height: responsiveHeight(6.5),
    },
    textbuttonorder1: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainWhite,
    },
    textbuttonorder2: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    webViewContainer: {
        flex: 1,
    },
});



export default StylePaymentMethod;