import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";


const StyleWallet = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveScreenHeight(1.5),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 10,
        // width: 40,
        // height: 40,
        marginLeft: responsiveScreenHeight(1),
        width: responsiveScreenHeight(4),
        height: responsiveScreenHeight(4),
    },
    title: {
        // fontSize: 19,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        left: responsiveScreenHeight(1),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconsearch: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveScreenHeight(1.5),
    },
    iconother: {
        // marginRight: 10,
        marginRight: responsiveScreenHeight(1.8),
    },
    viewcard: {
        // width: 350,
        // height: 180,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(19.8),
        alignSelf: 'center',
        backgroundColor: '#202020',
        // marginTop: 28,
        marginTop: responsiveScreenHeight(2),
        borderRadius: 25,
        elevation: 5,
    },
    viewcard1: {
        flexDirection: 'column',
        // marginTop: 20,
        // marginHorizontal: 20,
        // top: 5,
        marginTop: responsiveScreenHeight(2.3),
        marginHorizontal: responsiveScreenHeight(2.5),
        top: responsiveScreenHeight(0.5),
    },
    textcard1: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        color: Color.MainWhite,
        letterSpacing: 0.25,
        fontWeight: 'bold',
    },
    viewcard2: {
        flexDirection: 'row',
    },
    imagecard: {
        // width: 63,
        // height: 23,
        // marginLeft: 35,
        width: responsiveScreenHeight(7),
        height: responsiveScreenHeight(2.2),
        marginLeft: responsiveScreenHeight(4),
        top: responsiveScreenHeight(0.5),
    },
    imagecardmaster: {
        // width: 65,
        // height: 29,
        width: responsiveScreenHeight(7),
        height: responsiveScreenHeight(3.3),
        resizeMode: 'contain',
    },
    viewcard3: {
        flexDirection: 'column',
        // marginTop: 15,
        // marginHorizontal: 20,
        // gap: 10,
        marginTop: responsiveScreenHeight(1),
        marginHorizontal: responsiveScreenHeight(2.5),
        gap: responsiveScreenHeight(1.2),
    },
    textcard3: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
        letterSpacing: 0.25,
        top: responsiveScreenHeight(0.5),
    },
    textcardprice: {
        // fontSize: 29,
        fontSize: responsiveScreenFontSize(2.5),
        fontWeight: 'bold',
        color: Color.MainWhite,
        letterSpacing: 0.25,
    },
    viewcard4: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    viewcard5: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: 105,
        // height: 35,
        width: responsiveScreenHeight(12.5),
        height: responsiveScreenHeight(3.8),
        backgroundColor: Color.MainWhite,
        borderRadius: 20,
        justifyContent: 'space-evenly',
        // right: 5
    },
    textcardadd: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewhistory: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        marginTop: responsiveScreenHeight(2.5),
        justifyContent: 'space-between',
        // marginHorizontal: 24,
        marginHorizontal: responsiveScreenHeight(3),
    },
    history: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    texticon: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewlist: {
        // marginTop: 20,
        // marginHorizontal: 24,
        marginTop: responsiveScreenHeight(2.5),
        marginHorizontal: responsiveScreenHeight(3),
        // width: '90%',
        // height: '100%',
        width: responsiveScreenWidth(92),
    },
    viewitem: {
        flexDirection: 'column',
        // gap: 10,
        // marginBottom: 15,
        marginBottom: responsiveScreenHeight(1.8),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 10,
        gap: responsiveScreenHeight(1),
    },
    viewimage: {
        // width: 63,
        // height: 60,
        width: responsiveScreenHeight(6.8),
        height: responsiveScreenHeight(6.8),
        backgroundColor: Color.MainGray3,
        borderRadius: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        // width: 65,
        // height: 65,
        width: responsiveScreenHeight(6.5),
        height: responsiveScreenHeight(6.5),
    },
    viewtext: {
        flexDirection: 'column',
        // width: '75%',
        width: responsiveScreenWidth(68),
    },
    viewname: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // bottom: 7,
        bottom: responsiveScreenHeight(1),
    },
    textname: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textprice: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewtime: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // top: 2,
        top: responsiveScreenHeight(0.3),
    },
    texttime: {
        // fontSize: 13.5,
        fontSize: responsiveScreenFontSize(1.6),
        fontWeight: '400',
        color: Color.MainBlack,
        letterSpacing: 0.25
    },
    viewicon: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewiconup: {
        // width: 21,
        // height: 21,
        width: responsiveScreenHeight(2.3),
        height: responsiveScreenHeight(2.3),
        backgroundColor: Color.MainRed,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        // marginLeft: 2,
        // left: 8, 
        left: responsiveScreenHeight(0.8),
    },
});


export default StyleWallet;