import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveFontSize, responsiveHeight, responsiveWidth } from "react-native-responsive-dimensions";


const StyleWallet = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveHeight(2),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 10,
        // width: 40,
        // height: 40,
        marginLeft: responsiveHeight(1),
        width: responsiveHeight(4.8),
        height: responsiveHeight(4.8),
    },
    title: {
        // fontSize: 19,
        fontSize: responsiveFontSize(2.4),
        fontWeight: 'bold',
        left: responsiveHeight(1),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconsearch: {
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveHeight(1.5),
    },
    iconother: {
        // marginRight: 10,
        marginRight: responsiveHeight(1.8),
    },
    viewcard: {
        // width: 350,
        // height: 180,
        width: responsiveWidth(90),
        height: responsiveHeight(24),
        alignSelf: 'center',
        backgroundColor: '#202020',
        // marginTop: 28,
        marginTop: responsiveHeight(3.5),
        borderRadius: 25,
        elevation: 5,
    },
    viewcard1: {
        flexDirection: 'column',
        // marginTop: 20,
        // marginHorizontal: 20,
        // top: 5,
        marginTop: responsiveHeight(2.5),
        marginHorizontal: responsiveHeight(2.5),
        top: responsiveHeight(0.5),
    },
    textcard1: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        color: Color.MainWhite,
        letterSpacing: 0.25,
        fontWeight: 'bold',
    },
    viewcard2: {
        flexDirection: 'row',
    },
    imagecard: {
        // width: 63,
        // height: 23,
        // marginLeft: 35,
        width: responsiveHeight(7.5),
        height: responsiveHeight(2.7),
        marginLeft: responsiveHeight(4),
    },
    imagecardmaster: {
        // width: 65,
        // height: 29,
        width: responsiveHeight(7.8),
        height: responsiveHeight(3.5),
        resizeMode: 'contain',
    },
    viewcard3: {
        flexDirection: 'column',
        // marginTop: 15,
        // marginHorizontal: 20,
        // gap: 10,
        marginTop: responsiveHeight(1.8),
        marginHorizontal: responsiveHeight(2.5),
        gap: responsiveHeight(1.2),
    },
    textcard3: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        fontWeight: 'bold',
        color: Color.MainWhite,
        letterSpacing: 0.25,
    },
    textcardprice: {
        // fontSize: 29,
        fontSize: responsiveFontSize(3.6),
        fontWeight: 'bold',
        color: Color.MainWhite,
        letterSpacing: 0.25,
    },
    viewcard4: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    viewcard5: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: 105,
        // height: 35,
        width: responsiveHeight(12.5),
        height: responsiveHeight(4.2),
        backgroundColor: Color.MainWhite,
        borderRadius: 20,
        justifyContent: 'space-evenly',
        // right: 5
    },
    textcardadd: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewhistory: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        marginTop: responsiveHeight(3.5),
        justifyContent: 'space-between',
        // marginHorizontal: 24,
        marginHorizontal: responsiveHeight(3.3),
    },
    history: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    texticon: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewlist: {
        // marginTop: 20,
        // marginHorizontal: 24,
        marginTop: responsiveHeight(2.5),
        marginHorizontal: responsiveHeight(3.3),
        // width: '90%',
        // height: '100%',
        width: responsiveWidth(92),
    },
    viewitem: {
        flexDirection: 'column',
        // gap: 10,
        // marginBottom: 15,
        marginBottom: responsiveHeight(2),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 10,
        gap: responsiveHeight(1.2),
    },
    viewimage: {
        // width: 63,
        // height: 60,
        width: responsiveHeight(8.9),
        height: responsiveHeight(8.3),
        backgroundColor: Color.MainGray3,
        borderRadius: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        // width: 65,
        // height: 65,
        width: responsiveHeight(8),
        height: responsiveHeight(8),
    },
    viewtext: {
        flexDirection: 'column',
        // width: '75%',
        width: responsiveWidth(68),
    },
    viewname: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // bottom: 7,
        bottom: responsiveHeight(0.8),
    },
    textname: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textprice: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewtime: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // top: 2,
        top: responsiveHeight(0.3),
    },
    texttime: {
        // fontSize: 13.5,
        fontSize: responsiveFontSize(1.7),
        fontWeight: '400',
        color: Color.MainBlack,
        letterSpacing: 0.25
    },
    viewicon: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewiconup: {
        // width: 21,
        // height: 21,
        width: responsiveHeight(2.6),
        height: responsiveHeight(2.6),
        backgroundColor: Color.MainRed,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        // marginLeft: 2,
        // left: 8, 
        left: responsiveHeight(0.8),
    },
});


export default StyleWallet;