import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveFontSize, responsiveHeight, responsiveWidth } from "react-native-responsive-dimensions";

const StyleDetailHistory = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: responsiveHeight(2),
    },
    iconleft: {
        // marginLeft: 15,
        // top: 1,
        marginLeft: responsiveHeight(1.3),
        top: responsiveHeight(0.2),
    },
    textheader: {
        // fontSize: 20,
        fontSize: responsiveFontSize(2.4),
        fontFamily: 'Roboto-Bold',
        color: Color.MainBlack,
        // marginLeft: 13,
        left: responsiveHeight(1),
    },
    iconright: {
        // top: 1,
        top: responsiveHeight(0.2),
        marginLeft: 'auto',
        right: responsiveHeight(2),
    },
    viewlist: {
        // marginTop: 5,
        // marginHorizontal: 24,
        // width: '90%',
        // height: '100%',
        marginTop: responsiveHeight(0.5),
        marginHorizontal: responsiveHeight(2.5),
        width: responsiveWidth(90),
        height: responsiveHeight(70),
    },
    viewbarcode: {
        // width: '100%',
        // height: 200,
        width: responsiveWidth(100),
        height: responsiveHeight(25),
        alignItems: 'center',
        justifyContent: 'center',
    },
    barcode: {
        // width: 320,
        // height: 150,
        width: responsiveWidth(80),
        height: responsiveHeight(18),
    },
    viewlistitem: {

    },
    viewlistitemproduct: {
        flexDirection: 'row',
        // width: '100%',
        // height: 80,
        width: responsiveWidth(100),
        height: responsiveHeight(10.8),
        backgroundColor: Color.MainWhite,
        borderRadius: 8,
        elevation: 5,
        // marginBottom: 20,
        marginBottom: responsiveHeight(2.7),
    },
    viewitemnameimage: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginLeft: 13,
        // marginTop: 10,
        marginLeft: responsiveHeight(1.5),
        marginTop: responsiveHeight(1.3),
    },
    viewimageproduct: {
        // width: 55,
        // height: 55,
        width: responsiveHeight(7),
        height: responsiveHeight(7),
        borderRadius: 45,
        backgroundColor: Color.MainGray3,
        alignItems: 'center',
        justifyContent: 'center',
    },
    imageproduct: {
        // width: 55,
        // height: 55,
        width: responsiveHeight(7),
        height: responsiveHeight(7),
    },
    viewtextproduct: {
        flexDirection: 'column',
        // marginLeft: 20,
        // gap: 5,
        marginLeft: responsiveHeight(2.5),
        gap: responsiveHeight(0.5),
    },
    viewnameproduct: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewcolor: {
        // width: 20,
        // height: 20,
        width: responsiveHeight(2.5),
        height: responsiveHeight(2.5),
        borderRadius: 10,
        backgroundColor: Color.Black,
        marginLeft: responsiveHeight(1),
    },
    textname: {
        // fontSize: 16,
        fontSize: responsiveFontSize(1.8),
        fontFamily: 'Roboto-Bold',
        color: Color.MainBlack,
        width: responsiveWidth(50),
    },
    texthardwhite: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.7),
        fontWeight: '500',
        color: Color.MainGray,
        textAlign: 'justify',
    },
    viewcount: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    textcount: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.7),
        fontFamily: 'Roboto-Regular',
        color: Color.MainGray,
        // width: 180,
        width: responsiveWidth(50),
    },
    viewamountitem: {
        flexDirection: 'column',
        // width: '100%',
        // height: 160,
        width: responsiveWidth(90),
        height: responsiveHeight(21.5),
        backgroundColor: Color.MainWhite,
        borderRadius: 8,
        elevation: 5,
        marginBottom: responsiveHeight(2.7),
    },
    viewamount: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        // marginTop: 12,
        marginHorizontal: responsiveHeight(2.5),
        marginTop: responsiveHeight(1.5),
    },
    textamount: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.7),
        color: Color.MainGray,
        fontFamily: 'Roboto-Regular',
    },
    textamountitem: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.8),
        fontFamily: 'Roboto-Bold',
        color: Color.MainBlack,
    },
    line: {
        // width: '92%',
        width: responsiveWidth(83),
        height: 1,
        alignSelf: 'center',
        backgroundColor: Color.MainGray2,
        // marginTop: 10,
        marginTop: responsiveHeight(1.8),
    },
    viewstatus: {
        flexDirection: 'column',
        // width: '100%',
        // height: 160,
        width: responsiveWidth(90),
        height: responsiveHeight(21.5),
        backgroundColor: Color.MainWhite,
        borderRadius: 8,
        elevation: 5,
        // marginBottom: 20,
        marginBottom: responsiveHeight(2.7),
    },
    viewstatusitem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        // marginTop: 12,
        marginHorizontal: responsiveHeight(2.5),
        marginTop: responsiveHeight(1.5),
    },
    textstatus: {
        fontSize: responsiveFontSize(1.8),
        color: Color.MainGray,
        fontFamily: 'Roboto-Regular',
    },
    textstatusitem: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.9),
        fontFamily: 'Roboto-Bold',
        color: Color.MainBlack,
    },
    viewstatus1: {
        // width: 50,
        // height: 25,
        width: responsiveHeight(6.7),
        height: responsiveHeight(3.5),
        backgroundColor: Color.MainBlack,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    textstatusitem1: {
        // fontSize: 13,
        fontSize: responsiveFontSize(1.7),
        fontFamily: 'Roboto-Bold',
        color: Color.MainWhite,
    },
    textstatusitemleft: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.9),
        fontFamily: 'Roboto-Bold',
        color: Color.MainBlack,
        // left: 38,
        left: responsiveHeight(5.5),
    },
    viewcategory: {
        flexDirection: 'column',
        // width: '100%',
        // height: 50,
        width: responsiveWidth(90),
        height: responsiveHeight(6.9),
        backgroundColor: Color.MainWhite,
        borderRadius: 8,
        elevation: 5,
        marginBottom: responsiveHeight(2.7),
    },
    viewcategoryitem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 20,
        // marginTop: 10,
        marginHorizontal: responsiveHeight(2.5),
        marginTop: responsiveHeight(1.5),
    },
    textcategory: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.7),
        color: Color.MainGray,
        fontFamily: 'Roboto-Regular',
    },
    textorder: {
        // fontSize: 16,
        fontSize: responsiveFontSize(1.9),
        color: Color.MainBlack,
        fontFamily: 'Roboto-Bold',
        // left: 85,
        left: responsiveHeight(11.8),
    },
    icondown: {
        // marginLeft: 10,
    },
    viewshare: {
        // width: '50%',
        // height: 138,
        width: responsiveWidth(50),
        height: responsiveHeight(18.7),
        backgroundColor: Color.MainWhite,
        borderRadius: 8,
        elevation: 5,
        position: 'absolute',
        alignSelf: 'flex-end',
        // top: '7%',
        // right: 10,
        top: responsiveHeight(6.3),
        right: responsiveHeight(2.3),
        flexDirection: 'column',
        // gap: 10,
        gap: responsiveHeight(1.3),
    },
    viewshareitem: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 6,
        gap: responsiveHeight(0.8),
        // marginHorizontal: 15,
        // marginTop: 5,
        marginHorizontal: responsiveHeight(2),
        marginTop: responsiveHeight(0.5),
    },
    texticon: {
        // fontSize: 15,
        fontSize: responsiveFontSize(1.9),
        color: Color.MainBlack,
        fontFamily: 'Roboto-Bold',
    },
    linesmall: {
        // width: '100%',
        width: responsiveWidth(50),
        height: 1,
        backgroundColor: Color.MainGray2,
    },
});





export default StyleDetailHistory;