import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const styleShoeSDetail = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    header: {
        // width: '100%',
        // height: 325,
        width: responsiveScreenWidth(100),
        height: responsiveScreenHeight(34),
        backgroundColor: Color.Gray,
    },
    iconback: {
        // marginLeft: 15,
        // marginTop: 25,
        marginLeft: responsiveScreenWidth(3),
        marginTop: responsiveScreenHeight(2),
    },
    image: {
        // width: 330,
        // height: 175,
        width: responsiveScreenWidth(65),
        height: responsiveScreenHeight(19),
        alignSelf: 'center',
    },
    viewbody: {

    },
    namebody: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // marginTop: 18,
        // marginLeft: 15,
        // marginRight: 15,
        marginTop: responsiveScreenHeight(2),
        marginLeft: responsiveScreenWidth(3),
        marginRight: responsiveScreenWidth(3),
    },
    name: {
        // fontSize: 23,
        fontSize: responsiveScreenFontSize(2.7),
        fontWeight: '700',
        color: Color.MainBlack,
        fontFamily: 'Roboto-BlackItalic',
        fontStyle: 'italic',
    },
    iconheart: {

    },
    viewrating: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 12,
        // marginLeft: 12,
        // marginRight: 15,
        marginTop: responsiveScreenHeight(1.5),
        marginLeft: responsiveScreenWidth(2),
        marginRight: responsiveScreenWidth(3),
    },
    views: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.8),
        color: Color.MainBlack,
        fontWeight: '500',
        // width: 100,
        // height: 28,
        width: responsiveScreenWidth(20),
        height: responsiveScreenHeight(3),
        backgroundColor: Color.Gray,
        borderRadius: 10,
        justifyContent: 'center',
    },
    textviews: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.6),
        color: Color.MainBlack,
        fontWeight: '600',
        textAlignVertical: 'center',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    ratingreviews: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginLeft: 15,
        // gap: 5,
        marginLeft: responsiveScreenWidth(3),
        gap: responsiveScreenWidth(1),
    },
    rating: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        color: Color.MainBlack,
        fontStyle: 'italic',
    },
    line: {
        // width: 360,
        width: responsiveScreenWidth(93),
        height: 1.5,
        backgroundColor: Color.MainGray3,
        // marginTop: 18,
        marginTop: responsiveScreenHeight(2),
        alignSelf: 'center',
    },
    viewdescription: {
        // marginTop: 18,
        // marginLeft: 16,
        marginTop: responsiveScreenHeight(2),
        marginLeft: responsiveScreenWidth(3),
    },
    titledescription: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        color: Color.MainBlack,
        fontWeight: '600',
    },
    description: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        color: Color.MainBlack,
        // marginTop: 5,
        marginTop: responsiveScreenHeight(0.5),
        textAlign: 'justify',
        // width: 362,
        width: responsiveScreenWidth(92),
        // lineHeight: 22,
        lineHeight: responsiveScreenHeight(2.5),
    },
    viewmore: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.MainBlue,
        fontWeight: '600',
        // marginLeft: 2,
        // top: 5,
        marginLeft: responsiveScreenWidth(0.5),
        top: responsiveScreenHeight(0.5),
    },
    viewless: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        // top: 5,
        top: responsiveScreenHeight(0.5),
        color: Color.MainRed,
        fontWeight: '600',
        // marginLeft: 2,
        marginLeft: responsiveScreenWidth(0.5),
    },
    viewsize: {
        // marginTop: 5,
        // marginLeft: 16,
        marginTop: responsiveScreenHeight(1),
        marginLeft: responsiveScreenWidth(4),
        flexDirection: 'row',
    },
    titlesize: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        color: Color.MainBlack,
        fontWeight: '600',
    },
    titlecolor: {
        // fontSize: 18,\
        fontSize: responsiveScreenFontSize(2.1),
        color: Color.MainBlack,
        fontWeight: '600',
        // marginLeft: 125,
        marginLeft: responsiveScreenWidth(32),
    },
    viewitemrender: {
        flexDirection: 'row',
        // marginTop: 10,
        // width: '100%',
        marginTop: responsiveScreenHeight(1.5),
        width: responsiveScreenWidth(100),
    },
    itemsize: {
        // marginLeft: 15,
        marginLeft: responsiveScreenWidth(3),
        flexDirection: 'row',
        // gap: 10,
        gap: responsiveScreenWidth(2),
    },
    itemColor: {
        // marginLeft: 30,
        marginLeft: responsiveScreenWidth(8),
        flexDirection: 'row',
        // gap: 5,
        gap: responsiveScreenWidth(1.5),
    },
    viewquantity: {
        flexDirection: 'row',
        // marginTop: 30,
        // marginLeft: 15,
        marginTop: responsiveScreenHeight(3.5),
        marginLeft: responsiveScreenWidth(3.8),
    },
    titlequantity: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        color: Color.MainBlack,
        fontWeight: '600',
    },
    viewbuttonquantity: {
        flexDirection: 'row',
        // marginLeft: 40,
        left: responsiveScreenWidth(8),
        // width: 100,
        // height: 33,
        width: responsiveScreenWidth(25),
        height: responsiveScreenHeight(3.3),
        // bottom: 2,
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    iconminus: {
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(2),
    },
    quantity: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.MainBlack,
        fontWeight: '800',
    },
    iconplus: {
        // marginRight: 10,
        marginRight: responsiveScreenWidth(2),
    },
    viewtotalpriceAddcart: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        // marginTop: 33,
        // marginLeft: 15,
        marginTop: responsiveScreenHeight(3),
        marginLeft: responsiveScreenWidth(3),
    },
    viewtotalprice: {
        // marginTop: 1,
        left: responsiveScreenWidth(2),
    },
    titleprice: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.8),
        color: Color.MainGray,
        fontWeight: '600',
    },
    price: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.4),
        color: Color.MainBlack,
        fontWeight: '800',
    },
    addtocart: {
        flexDirection: 'row',
        // width: 240,
        // height: 50,
        width: responsiveScreenWidth(60),
        height: responsiveScreenHeight(5.8),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        // marginRight: 15,
        right: responsiveScreenWidth(3),
        elevation: 5,
        // gap: 15,
        gap: responsiveScreenWidth(4),
    },
    textaddcart: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        color: Color.MainWhite,
        fontWeight: '700',
        // marginRight: 10,
        marginRight: responsiveScreenWidth(2),
    },
});



export default styleShoeSDetail;