import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveWidth, responsiveFontSize, responsiveHeight } from "react-native-responsive-dimensions";


const styleCheckOutOrder = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveHeight(2),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerbartext: {
        // fontSize: 20,
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        // marginLeft: 10,
        left: responsiveWidth(2),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconback: {
        // marginLeft: 10,
        marginLeft: responsiveWidth(2),
    },
    iconother: {
        marginLeft: 'auto',
        // marginRight: 10,
        right: responsiveWidth(2.8),
        top: responsiveWidth(1),
    },
    body: {
        // marginTop: 25,
        marginTop: responsiveHeight(3),
        // marginHorizontal: 20,
        marginHorizontal: responsiveWidth(5),
    },
    address: {
        // marginBottom: 10,
        marginBottom: responsiveHeight(1.5),
    },
    addresstext: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginBottom: 20,
        marginBottom: responsiveHeight(2.3),
    },
    viewaddress: {
        // width: '100%',
        // height: 70,
    },
    lineorder: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 5,
        marginTop: responsiveHeight(0.6),
    },
    line: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 18,
        marginTop: responsiveHeight(2.3),
    },
    orderlist: {
        // marginTop: 22,
        // marginBottom: 10,
        marginTop: responsiveHeight(2.8),
        marginBottom: responsiveHeight(1.5),
    },
    orderlisttext: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    vieworderlist: {
        // marginTop: 18,
        marginTop: responsiveHeight(2.3),
        // marginBottom: 5,
        marginBottom: responsiveHeight(0.6)
    },
    viewrenderItem: {
        // width: '100%',
        // height: 120,
        height: responsiveHeight(15.3),
        elevation: 4,
        borderRadius: 15,
        backgroundColor: Color.MainWhite,
        justifyContent: 'center',
        // marginBottom: 15,
        marginBottom: responsiveHeight(2),
    },
    viewaddressitem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveWidth(3),
        // width: '100%',
        // height: 75,
        width: responsiveWidth(90),
        height: responsiveHeight(9.5),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        elevation: 5,
    },
    viewimageaddress: {
        // width: 50,
        // height: 50,
        width: responsiveWidth(12),
        height: responsiveWidth(12),
        backgroundColor: Color.MainGray3,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 10,
        marginLeft: responsiveWidth(4),
    },
    imageaddress: {
        // width: 30,
        // height: 30,
        width: responsiveWidth(7),
        height: responsiveWidth(7),
    },
    viewitemaddress: {
        flexDirection: 'column',
        gap: responsiveHeight(0.3),
    },
    viewiconedit: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconedit: {
        // marginLeft: '50%',
        marginLeft: responsiveWidth(45),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveWidth(3),
    },
    viewimage: {
        // width: 90,
        // height: 90,
        width: responsiveWidth(22),
        height: responsiveWidth(22),
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 10,
        marginLeft: responsiveWidth(4),
    },
    image: {
        // width: 100,
        // height: 100,
        width: responsiveWidth(23),
        height: responsiveWidth(23),
    },
    viewtext: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        // gap: 5,
        gap: responsiveHeight(0.7),
    },
    textname: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    hideiconedit: {
        // left: 100,
        // top: 12,
        left: responsiveWidth(24),
        top: responsiveHeight(1.5),
    },
    textsize: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.8),
        fontWeight: '800',
        color: Color.MainGray,
    },
    textprice: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewquantity: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // width: '63%',
        width: responsiveWidth(56),
    },
    textquantity: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // width: 30,
        // height: 30,
        width: responsiveWidth(7),
        height: responsiveWidth(7),
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    textchooseshipping: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginTop: 25,
        marginTop: responsiveHeight(3),
    },
    viewshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        // gap: 12,
        marginTop: responsiveHeight(3),
        gap: responsiveWidth(3),
        // width: '100%',
        // height: 60,
        width: responsiveWidth(90),
        height: responsiveHeight(9),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
        // marginBottom: 15,
        marginBottom: responsiveHeight(2),
    },
    viewshippingitem: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 5,
        // gap: 18,
        marginTop: responsiveHeight(0.6),
        gap: responsiveWidth(4),
        // width: '100%',
        width: responsiveWidth(90),
        // height: 60,
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
    },
    iconship: {
        // marginLeft: 15,
        marginLeft: responsiveWidth(3.5),
    },
    viewiconitemship: {
        // width: 50,
        // height: 50,
        width: responsiveWidth(12),
        height: responsiveWidth(12),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        // left: 7,
        left: responsiveWidth(1.5),
    },
    iconshipitem: {

    },
    iconright: {
        marginLeft: 'auto',
        // marginRight: 13,
        marginRight: responsiveWidth(3),
        elevation: 5,
    },
    textshipping: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textshippingitem: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.8),
        fontWeight: '700',
        color: Color.MainGray,
        letterSpacing: 0.25,
    },
    textpromocode: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginTop: 25,
        marginTop: responsiveHeight(3),
    },
    viewpromocode: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        // width: '80%',
        // height: 50,
        width: responsiveWidth(75),
        height: responsiveHeight(6.2),
        gap: 15,
    },
    textpromocodeitem: {
        // fontSize: 17,
        fontSize: responsiveFontSize(2.1),
        fontWeight: '700',
        color: Color.MainWhite,
        letterSpacing: 0.35,
        // marginLeft: '22%',
        marginLeft: responsiveWidth(19),
    },
    promcode: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        // gap: 18,
        marginTop: responsiveHeight(3),
        gap: responsiveWidth(4),
    },
    inputpromcode: {
        // width: '83%',
        width: responsiveWidth(78),
        // height: 50,
        height: responsiveHeight(6.2),
        backgroundColor: Color.MainWhite,
        borderRadius: 10,
        // paddingLeft: 15,
        paddingLeft: responsiveWidth(3.5),
        // fontSize: 15,
        fontSize: responsiveFontSize(1.8),
        elevation: 5,
    },
    viewtotalbill: {
        flexDirection: 'column',
        // marginTop: 25,
        // gap: 15,
        marginTop: responsiveHeight(3),
        gap: responsiveHeight(1.8),
        // width: '100%',
        // height: 180,
        width: responsiveWidth(90),
        height: responsiveHeight(22.5),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
    },
    viewamount: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginTop: 25,
        // marginHorizontal: 15,
        marginTop: responsiveHeight(3),
        marginHorizontal: responsiveWidth(4),
    },
    textamount: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewtotalshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 15,
        marginHorizontal: responsiveWidth(4),
    },
    texttotalshipping: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    textpricetotalshipping: {
        // fontSize: 15,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    linetotal: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 5,
        // marginBottom: 15,
        marginTop: responsiveHeight(0.6),
        marginBottom: responsiveHeight(2),
    },
    viewtotal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 15,
        // bottom: 18,
        marginHorizontal: responsiveWidth(4),
        bottom: responsiveHeight(2.3),
    },
    texttotal: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewbutton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // marginTop: 25,
        // marginBottom: 25,
        marginTop: responsiveHeight(3),
        marginBottom: responsiveHeight(3),
    },
    button: {
        flexDirection: 'row',
        // width: '90%',
        // height: 50,
        width: responsiveWidth(85),
        height: responsiveHeight(7),
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 15,
    },
    textbutton: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },

});


export default styleCheckOutOrder;