import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenWidth, responsiveScreenFontSize, responsiveScreenHeight } from "react-native-responsive-dimensions";


const styleCheckOutOrder = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveScreenHeight(2),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerbartext: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.5),
        fontWeight: 'bold',
        // marginLeft: 10,
        left: responsiveScreenWidth(2),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconback: {
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(2),
    },
    iconother: {
        marginLeft: 'auto',
        // marginRight: 10,
        right: responsiveScreenWidth(2.8),
        top: responsiveScreenWidth(1),
    },
    body: {
        // marginTop: 25,
        marginTop: responsiveScreenHeight(3),
        // marginHorizontal: 20,
        marginHorizontal: responsiveScreenWidth(5),
    },
    address: {
        // marginBottom: 10,
        marginBottom: responsiveScreenHeight(1.5),
    },
    addresstext: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginBottom: 20,
        marginBottom: responsiveScreenHeight(2.3),
    },
    viewaddress: {
        // width: '100%',
        // height: 70,
    },
    lineorder: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 5,
        marginTop: responsiveScreenHeight(0.6),
    },
    line: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 18,
        marginTop: responsiveScreenHeight(2.3),
    },
    orderlist: {
        // marginTop: 22,
        // marginBottom: 10,
        marginTop: responsiveScreenHeight(2.8),
        marginBottom: responsiveScreenHeight(1),
    },
    orderlisttext: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    vieworderlist: {
        // marginTop: 18,
        marginTop: responsiveScreenHeight(2.3),
        // marginBottom: 5,
        marginBottom: responsiveScreenHeight(0.6)
    },
    viewrenderItem: {
        // width: '100%',
        // height: 120,
        height: responsiveScreenHeight(12),
        elevation: 4,
        borderRadius: 15,
        backgroundColor: Color.MainWhite,
        justifyContent: 'center',
        // marginBottom: 15,
        marginBottom: responsiveScreenHeight(2),
    },
    viewaddressitem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveScreenWidth(3),
        // width: '100%',
        // height: 75,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(8.5),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        elevation: 5,
    },
    viewimageaddress: {
        // width: 50,
        // height: 50,
        width: responsiveScreenWidth(11),
        height: responsiveScreenWidth(11),
        backgroundColor: Color.MainGray3,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(2),
    },
    imageaddress: {
        // width: 30,
        // height: 30,
        width: responsiveScreenWidth(7),
        height: responsiveScreenWidth(7),
    },
    viewitemaddress: {
        flexDirection: 'column',
        gap: responsiveScreenHeight(0.3),
    },
    viewiconedit: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconedit: {
        // marginLeft: '50%',
        marginLeft: responsiveScreenWidth(48),
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveScreenWidth(3),
    },
    viewimage: {
        // width: 90,
        // height: 90,
        width: responsiveScreenWidth(19),
        height: responsiveScreenWidth(19),
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(4),
    },
    image: {
        // width: 100,
        // height: 100,
        width: responsiveScreenWidth(20),
        height: responsiveScreenWidth(20),
    },
    viewtext: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        // gap: 5,
        gap: responsiveScreenHeight(0.7),
    },
    textname: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    hideiconedit: {
        // left: 100,
        // top: 12,
        left: responsiveScreenWidth(29),
        top: responsiveScreenHeight(1.5),
    },
    textsize: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: '800',
        color: Color.MainGray,
        right: responsiveScreenWidth(0.3),
    },
    textprice: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewquantity: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // width: '63%',
        width: responsiveScreenWidth(60),
    },
    textquantity: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // width: 30,
        // height: 30,
        width: responsiveScreenWidth(6),
        height: responsiveScreenWidth(6),
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    textchooseshipping: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginTop: 25,
        marginTop: responsiveScreenHeight(3),
    },
    viewshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        // gap: 12,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenWidth(3),
        // width: '100%',
        // height: 60,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(8.9),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
        // marginBottom: 15,
        marginBottom: responsiveScreenHeight(2),
    },
    viewshippingitem: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 5,
        // gap: 18,
        marginTop: responsiveScreenHeight(0.6),
        gap: responsiveScreenWidth(3),
        // width: '100%',
        width: responsiveScreenWidth(90),
        // height: 60,
        height: responsiveScreenHeight(6.5),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
    },
    iconship: {
        // marginLeft: 15,
        marginLeft: responsiveScreenWidth(3.5),
    },
    viewiconitemship: {
        // width: 50,
        // height: 50,
        width: responsiveScreenWidth(11),
        height: responsiveScreenWidth(11),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        // left: 7,
        marginLeft: responsiveScreenWidth(3),
    },
    iconshipitem: {
        
    },
    iconright: {
        marginLeft: 'auto',
        // marginRight: 13,
        marginRight: responsiveScreenWidth(3),
        elevation: 5,
    },
    textshipping: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textshippingitem: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: '700',
        color: Color.MainGray,
        letterSpacing: 0.25,
    },
    textpromocode: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginTop: 25,
        marginTop: responsiveScreenHeight(3),
    },
    viewpromocode: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        // width: '80%',
        // height: 50,
        width: responsiveScreenWidth(75),
        height: responsiveScreenHeight(6),
        gap: 15,
    },
    textpromocodeitem: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '700',
        color: Color.MainWhite,
        letterSpacing: 0.35,
        // marginLeft: '22%',
        marginLeft: responsiveScreenWidth(19),
    },
    promcode: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 25,
        // gap: 18,
        marginTop: responsiveScreenHeight(3),
        gap: responsiveScreenWidth(4),
    },
    inputpromcode: {
        // width: '83%',
        width: responsiveScreenWidth(78),
        // height: 50,
        height: responsiveScreenHeight(5.8),
        backgroundColor: Color.MainWhite,
        borderRadius: 10,
        // paddingLeft: 15,
        paddingLeft: responsiveScreenWidth(3.5),
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.8),
        elevation: 5,
    },
    viewtotalbill: {
        flexDirection: 'column',
        // marginTop: 25,
        // gap: 15,
        marginTop: responsiveScreenHeight(3),
        gap: responsiveScreenHeight(1.8),
        // width: '100%',
        // height: 180,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(21.8),
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
    },
    viewamount: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginTop: 25,
        // marginHorizontal: 15,
        marginTop: responsiveScreenHeight(3),
        marginHorizontal: responsiveScreenWidth(4),
    },
    textamount: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewtotalshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 15,
        marginHorizontal: responsiveScreenWidth(4),
    },
    texttotalshipping: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    textpricetotalshipping: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    linetotal: {
        height: 1,
        backgroundColor: Color.MainGray3,
        // marginTop: 5,
        // marginBottom: 15,
        marginTop: responsiveScreenHeight(0.6),
        marginBottom: responsiveScreenHeight(2),
    },
    viewtotal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // marginHorizontal: 15,
        // bottom: 18,
        marginHorizontal: responsiveScreenWidth(4),
        bottom: responsiveScreenHeight(2.3),
    },
    texttotal: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewbutton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // marginTop: 25,
        // marginBottom: 25,
        marginTop: responsiveScreenHeight(3),
        marginBottom: responsiveScreenHeight(3),
    },
    button: {
        flexDirection: 'row',
        // width: '90%',
        // height: 50,
        width: responsiveScreenWidth(85),
        height: responsiveScreenHeight(6),
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 15,
    },
    textbutton: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },

});


export default styleCheckOutOrder;