import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";


const styleCheckOutOrder = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        marginTop: 25,
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerbartext: {
        fontSize: 20,
        fontWeight: 'bold',
        marginLeft: 10,
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconback: {
        marginLeft: 10,
    },
    iconother: {
        marginLeft: 'auto',
        marginRight: 10,
        top: 2,
    },
    body: {
        marginTop: 25,
        marginHorizontal: 20,
    },
    address: {
        marginBottom: 10,
    },
    addresstext: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        marginBottom: 20,
    },
    viewaddress: {
        width: '100%',
        height: 70,
    },
    lineorder: {
        height: 1,
        backgroundColor: Color.MainGray3,
        marginTop: 5,
    },
    line: {
        height: 1,
        backgroundColor: Color.MainGray3,
        marginTop: 18,
    },
    orderlist: {
        marginTop: 22,
        marginBottom: 10,
    },
    orderlisttext: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    vieworderlist: {
        marginTop: 18,
        marginBottom: 5,
        width: '100%',
    },
    viewrenderItem: {
        width: '100%',
        height: 120,
        elevation: 4,
        borderRadius: 15,
        backgroundColor: Color.MainWhite,
        justifyContent: 'center',
        marginBottom: 15,
    },
    viewaddressitem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
        width: '100%',
        height: 75,
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        elevation: 5,
    },
    viewimageaddress: {
        width: 50,
        height: 50,
        backgroundColor: Color.MainGray3,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
    },
    backgroundimage: {
        width: 20,
        height: 20,
        backgroundColor: Color.MainWhite,
        borderRadius: 15,
        position: 'absolute',
    },
    imageaddress: {
        width: 30,
        height: 30,
    },
    viewitemaddress: {
        flexDirection: 'column',
        gap: 2,
    },
    viewiconedit: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconedit: {
        marginLeft: '50%',
    },
    viewproduct: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    viewimage: {
        width: 90,
        height: 90,
        backgroundColor: Color.MainGray3,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
    },
    image: {
        width: 100,
        height: 100,
    },
    viewtext: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        gap: 5,
    },
    textname: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    hideiconedit: {
        left: 100,
        top: 12,
    },
    textsize: {
        fontSize: 14,
        fontWeight: '800',
        color: Color.MainGray,
    },
    textprice: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewquantity: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '63%',
    },
    textquantity: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Color.MainBlack,
        width: 30,
        height: 30,
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    textchooseshipping: {
        fontSize: 18,
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        marginTop: 25,
    },
    viewshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 25,
        gap: 12,
        width: '100%',
        height: 60,
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
        marginBottom: 15,
    },
    viewshippingitem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
        gap: 18,
        width: '100%',
        height: 60,
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
    },
    iconship: {
        marginLeft: 15,
    },
    viewiconitemship: {
        width: 50,
        height: 50,
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        left: 7,
    },
    iconshipitem: {

    },
    iconright: {
        marginLeft: 'auto',
        marginRight: 13,
        elevation: 5,
    },
    textshipping: {
        fontSize: 18,
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    textshippingitem: {
        fontSize: 14,
        fontWeight: '700',
        color: Color.MainGray,
        letterSpacing: 0.25,
    },
    textpromocode: {
        fontSize: 18,
        fontWeight: '700',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        marginTop: 25,
    },
    viewpromocode: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        width: '80%',
        height: 50,
        gap: 15,
    },
    textpromocodeitem: {
        fontSize: 17,
        fontWeight: '700',
        color: Color.MainWhite,
        letterSpacing: 0.35,
        marginLeft: '22%',
    },
    promcode: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 25,
        gap: 18,
    },
    inputpromcode: {
        width: '83%',
        height: 50,
        backgroundColor: Color.MainWhite,
        borderRadius: 10,
        paddingLeft: 15,
        fontSize: 15,
        elevation: 5,
    },
    viewtotalbill: {
        flexDirection: 'column',
        marginTop: 25,
        gap: 15,
        width: '100%',
        height: 180,
        backgroundColor: Color.MainWhite,
        alignSelf: 'center',
        borderRadius: 15,
        justifyContent: 'center',
        elevation: 5,
    },
    viewamount: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 25,
        marginHorizontal: 15,
    },
    textamount: {
        fontSize: 15,
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewtotalshipping: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginHorizontal: 15,
    },
    texttotalshipping: {
        fontSize: 15,
        fontWeight: '500',
        color: Color.MainBlack,
    },
    textpricetotalshipping: {
        fontSize: 15,
        fontWeight: '500',
        color: Color.MainBlack,
    },
    linetotal: {
        height: 1,
        backgroundColor: Color.MainGray3,
        marginTop: 5,
        marginBottom: 15,
    },
    viewtotal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginHorizontal: 15,
        bottom: 18,
    },
    texttotal: {
        fontSize: 16,
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewbutton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 25,
        marginBottom: 25,
    },
    button: {
        flexDirection: 'row',
        width: '90%',
        height: 50,
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 15,
    },
    textbutton: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Color.MainWhite,
    },

});


export default styleCheckOutOrder;