import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveWidth, responsiveFontSize, responsiveHeight } from "react-native-responsive-dimensions";

const styleMyCart = StyleSheet.create({
    rootContainerStyle: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    contentContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)', // Màu nền mờ
    },
    header: {
        marginTop: responsiveHeight(2),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerbaricon: {
        // width: 38,
        // height: 38,
        width: responsiveWidth(9),
        height: responsiveWidth(9),
        marginLeft: responsiveWidth(2),
    },
    headerbartext: {
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        // marginLeft: 10,
        left: responsiveWidth(2),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconsearch: {
        marginLeft: 'auto',
        // marginRight: 10,
        // top: 2,
        right: responsiveWidth(2),
        top: responsiveWidth(1.2),
    },
    viewMycart: {

    },
    viewcheckout: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-around',
        position: 'absolute',
        bottom: 0,
        width: responsiveWidth(100),
        // height: 120,
        height: responsiveHeight(22),
        backgroundColor: Color.MainWhite,
        alignSelf: 'flex-start',
        alignContent: 'flex-start',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        elevation: 5,
    },
    viewcheckout1: {
        flexDirection: 'column',
        marginRight: 'auto',
        // marginLeft: 20,
        // marginTop: 24,
        marginLeft: responsiveWidth(5.2),
        marginTop: responsiveHeight(3.1),
    },
    texttotal: {
        // fontSize: 14,
        fontSize: responsiveFontSize(1.8),
    },
    textcheckout: {
        // fontSize: 20,
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewcheckout2: {
        flexDirection: 'row',
        // width: 190,
        // height: 53,
        width: responsiveWidth(45),
        height: responsiveHeight(7),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        right: responsiveWidth(5.5),
        marginTop: responsiveHeight(2.5),
        gap: responsiveWidth(2),
        elevation: 5,
    },
    textcheckout2: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    viewcart: {

    },
    viewcartbody: {
        flexDirection: 'row',
    },
    viewcart1: {
        flexDirection: 'row',
        // gap: 15,
        gap: responsiveWidth(3.5),
        // marginTop: 20,
        marginTop: responsiveHeight(2.6),
        left: responsiveWidth(2.8),
        backgroundColor: Color.MainWhite,
        // width: '95%',
        // height: 125,
        height: responsiveHeight(15.5),
        borderRadius: 20,
        alignSelf: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    viewcart1img: {
        // width: 95,
        // height: 90,
        width: responsiveWidth(23),
        height: responsiveHeight(11),
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        // marginLeft: 10,
        marginLeft: responsiveWidth(3),
    },
    viewcart1text: {
        flexDirection: 'column',
        // gap: 15,
        // marginLeft: 2,
        marginLeft: responsiveWidth(0.3),
        gap: responsiveWidth(3),
    },
    viewcart1text1: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: responsiveWidth(64.5),
    },
    cart1text3: {
        // fontSize: 13,
        // right: 2,
        // color: Color.MainGray,
        // fontWeight: '500',
        // bottom: 3,
        fontSize: responsiveFontSize(1.8),
        right: responsiveWidth(0.5),
        color: Color.MainGray,
        fontWeight: '500',
        bottom: responsiveHeight(0.3),
    },
    cart1text1: {
        // fontSize: 18,
        // fontWeight: 'bold',
        // color: Color.MainBlack,
        // right: 2,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        right: responsiveWidth(0.5),
    },
    cart1text2: {
        // fontSize: 16,
        // fontWeight: 'bold',
        // color: Color.MainBlack,
        // bottom: 5,
        // right: 2,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        bottom: responsiveHeight(0.6),
        right: responsiveWidth(0.5),
    },
    Flashviewcart: {
        // width: '100%',
        // height: '100%',
        height: responsiveHeight(100),
    },
    viewicondelelte: {
        // left: 'auto',
        // marginLeft: 'auto',
        right: responsiveWidth(4),
    },
    viewcart2: {
        alignSelf: 'flex-end',
        // right: 103,
        // bottom: 18,
        right: responsiveWidth(23),
        bottom: responsiveHeight(2.2),
    },
    viewcart2text: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '98%',
        // height: 32,
        width: responsiveWidth(23),
        height: responsiveHeight(4),
        backgroundColor: Color.Gray,
        borderRadius: 15,
        gap: responsiveWidth(3.5),
    },
    viewcart2bottomtext: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '98%',
        // height: 32,
        width: responsiveWidth(23),
        height: responsiveHeight(4),
        backgroundColor: Color.Gray,
        borderRadius: 15,
        gap: responsiveWidth(3.5),
        // right: '51%',
        right: responsiveWidth(19),
    },
    viewcart2text1: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    viewiconminus: {
        // marginLeft: 5,
        marginLeft: responsiveWidth(1.2),
    },
    bottomSheetText: {
        // fontSize: 18,
        fontSize: responsiveFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    line: {
        // width: '80%',
        width: responsiveWidth(85),
        height: 1,
        backgroundColor: Color.MainGray,
        alignSelf: 'center',
        marginTop: responsiveHeight(2),
    },
    viewbottomcontainer: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 10,
        gap: responsiveWidth(2.5),
        // marginTop: 20,
        marginTop: responsiveHeight(2.6),
        alignSelf: 'center',
        // marginBottom: 15,
        marginBottom: responsiveHeight(1.8),
        // width: '93%',
        width: responsiveWidth(93),
        // height: 125,
        height: responsiveHeight(16),
        backgroundColor: Color.MainWhite,
        borderRadius: 25,
        elevation: 6,
    },
    bottomSheetImage: {
        // width: 100,
        // height: 100,
        width: responsiveWidth(24),
        height: responsiveHeight(12),
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        // marginLeft: 12,
        marginLeft: responsiveWidth(3.8),
    },
    viewbottomItem: {
        flexDirection: 'column',
        // gap: 16,
        // bottom: 8,
        gap: responsiveWidth(4),
        bottom: responsiveHeight(1),
    },
    bottomSheetProduct: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // marginTop: 12,
        marginTop: responsiveHeight(1.5),
    },
    bottomSheetText1: {
        // fontSize: 13,
        fontSize: responsiveFontSize(1.8),
        fontWeight: '500',
        color: Color.MainGray,
    },
    bottomSheetText2: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    bottomSheetButtonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        top: responsiveHeight(3),
    },
    bottomSheetButtonGray: {
        // width: 160,
        // height: 45,
        width: responsiveWidth(40),
        height: responsiveHeight(6),
        backgroundColor: Color.MainGray3,
        borderRadius: 25,
    },
    bottomSheetButtonWhite: {
        // width: 160,
        // height: 45,
        width: responsiveWidth(40),
        height: responsiveHeight(6),
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
    },
    bottomSheetButtonTextGray: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // marginTop: 8,
        top: responsiveHeight(1.5),
        textAlign: 'center',
    },
    bottomSheetButtonTextWhite: {
        // fontSize: 16,
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
        textAlign: 'center',
        top: responsiveHeight(1.5),
    },
    viewcontainernoorder: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
});


export default styleMyCart;