import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenWidth, responsiveScreenFontSize, responsiveScreenHeight } from "react-native-responsive-dimensions";

const styleMyCart = StyleSheet.create({
    rootContainerStyle: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    contentContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)', // Màu nền mờ
    },
    header: {
        marginTop: responsiveScreenHeight(1.5),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerbaricon: {
        // width: 38,
        // height: 38,
        width: responsiveScreenWidth(9),
        height: responsiveScreenWidth(9),
        marginLeft: responsiveScreenWidth(2),
    },
    headerbartext: {
        fontSize: responsiveScreenFontSize(2.5),
        fontWeight: 'bold',
        // marginLeft: 10,
        left: responsiveScreenWidth(2),
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    iconsearch: {
        marginLeft: 'auto',
        // marginRight: 10,
        // top: 2,
        right: responsiveScreenWidth(2),
        top: responsiveScreenWidth(1.2),
    },
    containernoroder: {
        top: responsiveScreenHeight(20),
    },
    viewimage: {
        // width: '100%',
        // height: 200,
        justifyContent: 'center',
        alignItems: 'center',

    },
    image: {
        width: responsiveScreenHeight(25),
        height: responsiveScreenHeight(25),
        resizeMode: 'contain',
    },
    viewtext: {
        justifyContent: 'center',
        alignItems: 'center',
        // marginTop: 20,
        // gap: 8,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(1),
    },
    text1: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    text2: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
    },
    viewcheckout: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-around',
        position: 'absolute',
        bottom: 0,
        width: responsiveScreenWidth(100),
        // height: 120,
        height: responsiveScreenHeight(19),
        backgroundColor: Color.MainWhite,
        alignSelf: 'flex-start',
        alignContent: 'flex-start',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        elevation: 5,
    },
    viewcheckout1: {
        flexDirection: 'column',
        marginRight: 'auto',
        // marginLeft: 20,
        // marginTop: 24,
        marginLeft: responsiveScreenWidth(6.5),
        marginTop: responsiveScreenHeight(3.1),
    },
    texttotal: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.8),
    },
    textcheckout: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    viewcheckout2: {
        flexDirection: 'row',
        // width: 190,
        // height: 53,
        width: responsiveScreenWidth(45),
        height: responsiveScreenHeight(6),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        right: responsiveScreenWidth(5.5),
        marginTop: responsiveScreenHeight(2.5),
        gap: responsiveScreenWidth(2),
        elevation: 5,
    },
    textcheckout2: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    viewcart: {

    },
    viewcartbody: {
        flexDirection: 'row',
    },
    viewcart1: {
        flexDirection: 'row',
        // gap: 15,
        gap: responsiveScreenWidth(3.5),
        // marginTop: 20,
        marginTop: responsiveScreenHeight(2.6),
        left: responsiveScreenWidth(4.7),
        backgroundColor: Color.MainWhite,
        // width: '95%',
        // height: 125,
        height: responsiveScreenHeight(12.8),
        borderRadius: 20,
        alignSelf: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    viewcart1img: {
        // width: 95,
        // height: 90,
        width: responsiveScreenWidth(19),
        height: responsiveScreenHeight(9),
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(3),
    },
    viewcart1text: {
        flexDirection: 'column',
        // gap: 15,
        // marginLeft: 2,
        marginLeft: responsiveScreenWidth(0.3),
        gap: responsiveScreenWidth(3),
    },
    viewcart1text1: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: responsiveScreenWidth(64.5),
    },
    cart1text3: {
        // fontSize: 13,
        // right: 2,
        // color: Color.MainGray,
        // fontWeight: '500',
        // bottom: 3,
        fontSize: responsiveScreenFontSize(1.7),
        right: responsiveScreenWidth(0.5),
        color: Color.MainGray,
        fontWeight: '500',
        bottom: responsiveScreenHeight(0.3),
    },
    cart1text1: {
        // fontSize: 18,
        // fontWeight: 'bold',
        // color: Color.MainBlack,
        // right: 2,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        right: responsiveScreenWidth(0.5),
    },
    cart1text2: {
        // fontSize: 16,
        // fontWeight: 'bold',
        // color: Color.MainBlack,
        // bottom: 5,
        // right: 2,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        bottom: responsiveScreenHeight(0.6),
        right: responsiveScreenWidth(0.5),
    },
    Flashviewcart: {
        // width: '100%',
        // height: '100%',
        height: responsiveScreenHeight(100),
    },
    viewicondelelte: {
        // left: 'auto',
        // marginLeft: 'auto',
        right: responsiveScreenWidth(4),
    },
    viewcart2: {
        alignSelf: 'flex-end',
        // right: 103,
        // bottom: 18,
        right: responsiveScreenWidth(23),
        bottom: responsiveScreenHeight(2.2),
    },
    viewcart2text: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '98%',
        // height: 32,
        width: responsiveScreenWidth(23),
        height: responsiveScreenHeight(3.5),
        backgroundColor: Color.Gray,
        borderRadius: 15,
        gap: responsiveScreenWidth(3.5),
        left: responsiveScreenWidth(3),
    },
    viewcart2bottomtext: {
        flexDirection: 'row',
        alignItems: 'center',
        // width: '98%',
        // height: 32,
        width: responsiveScreenWidth(23),
        height: responsiveScreenHeight(3.5),
        backgroundColor: Color.Gray,
        borderRadius: 15,
        gap: responsiveScreenWidth(3.5),
        top: responsiveScreenHeight(4),
        right: responsiveScreenWidth(3),
        // right: '51%',
    },
    viewcart2text1: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    viewiconminus: {
        // marginLeft: 5,
        marginLeft: responsiveScreenWidth(1.8),
    },
    bottomSheetText: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        textAlign: 'center',
    },
    line: {
        // width: '80%',
        width: responsiveScreenWidth(85),
        height: 1,
        backgroundColor: Color.MainGray,
        alignSelf: 'center',
        marginTop: responsiveScreenHeight(2),
    },
    viewbottomcontainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        // gap: 10,
        gap: responsiveScreenWidth(2.5),
        // marginTop: 20,
        marginTop: responsiveScreenHeight(2.6),
        alignSelf: 'center',
        // marginBottom: 15,
        marginBottom: responsiveScreenHeight(1.8),
        // width: '93%',
        width: responsiveScreenWidth(94),
        // height: 125,
        height: responsiveScreenHeight(15),
        backgroundColor: Color.MainWhite,
        borderRadius: 25,
        elevation: 6,
    },
    bottomSheetImage: {
        // width: 100,
        // height: 100,
        width: responsiveScreenWidth(22),
        height: responsiveScreenHeight(10),
        backgroundColor: Color.MainGray3,
        borderRadius: 15,
        // marginLeft: 12,
        marginLeft: responsiveScreenWidth(3.8),
    },
    viewbottomItem: {
        flexDirection: 'column',
        // gap: 16,
        // bottom: 8,
        gap: responsiveScreenWidth(4),
        bottom: responsiveScreenHeight(0.8),
    },
    bottomSheetProduct: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // marginTop: 12,
        marginTop: responsiveScreenHeight(1.5),
    },
    bottomSheetText1: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: '500',
        color: Color.MainGray,
    },
    bottomSheetText2: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
        width: responsiveScreenWidth(20),
    },
    bottomSheetButtonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        top: responsiveScreenHeight(3),
    },
    bottomSheetButtonGray: {
        // width: 160,
        // height: 45,
        width: responsiveScreenWidth(40),
        height: responsiveScreenHeight(5.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 25,
    },
    bottomSheetButtonWhite: {
        // width: 160,
        // height: 45,
        width: responsiveScreenWidth(40),
        height: responsiveScreenHeight(5.5),
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
    },
    bottomSheetButtonTextGray: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        // marginTop: 8,
        top: responsiveScreenHeight(1.5),
        textAlign: 'center',
    },
    bottomSheetButtonTextWhite: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
        textAlign: 'center',
        top: responsiveScreenHeight(1.5),
    },
    viewcontainernoorder: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
});


export default styleMyCart;