
const Theme = {
    light: {
        theme: 'light',
        color: '#000',
        fullblack: '#000',
        container: '#FFFFFF',
        backgroundColor: 'white',
        image: require('../assets/images/logoflash.png'),
        line: {
            height: 1,
            backgroundColor: '#535861',
            width: 350,
            alignSelf: 'center',
        },
        centertab: '#F9F9FA',
        backgroundCheckOut: 'black',
        backgroundPorfile: 'white',
        colorTextWhiteBlack: '#fff',
        displayColor: '#F8F8F8',
        backgroundBorder: '#F3F3F3',
        backgroundBorderTwo: '#F3F3F3',
        backgroundPaymentModal: '#fff',
        bordercolor: '#F3F3F3',
        backgroundInvite: '#000',
        backgroundView: '#FFFFFF',
        backgroundModalReceipt: '#F3F3F3',
        backgroundestatus: '#000',
        notifeeView: '#fff',
        imageBorder: '#DFDFDF',
        centerbackground: '#fff',
        buttonview: 'gray',
        backgroundFill: '#000',
    },
    dark: {
        theme: 'dark',
        color: '#fff',
        fullblack: 'gray',
        container: '#000',
        backgroundColor: 'black',
        image: require('../assets/images/logoflashblack.jpg'),
        line: {
            height: 1,
            backgroundColor: '#535861',
            width: 350,
            alignSelf: 'center',
        },
        backgroundCheckOut: 'white',
        backgroundPorfile: '#181A20',
        colorTextWhiteBlack: '#000',
        displayColor: '#000',
        backgroundInvite: '#181A20',
        backgroundBorder: '#181A20',
        backgroundBorderTwo: '#181A20',
        backgroundModalReceipt: '#1c1c1c',
        backgroundPaymentModal: '#181A20',
        bordercolor: '#393939',
        backgroundView: '#1c1c1c',
        backgroundestatus: '#35373E',
        notifeeView: '#35383F',
        imageBorder: '#35383F',
        centerbackground: 'gray',
        buttonview: 'white',
        backgroundFill: 'gray',
        centertab: '#000',
    },
}


export default Theme;