import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StyleAddNewress = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    body: {
        backgroundColor: Color.MainWhite,
        // marginTop: 30,
        // gap: 20,
        marginTop: responsiveScreenHeight(1.5),
        gap: responsiveScreenHeight(2),
    },
    viewheader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 8,
        // top: 1,
        marginLeft: responsiveScreenWidth(2),
        top: responsiveScreenHeight(0.2),
        color: Color.MainBlack,
    },
    textheader: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        fontWeight: 'bold',
        // marginLeft: 14,
        left: responsiveScreenWidth(3),
        color: Color.MainBlack,
    },
    viewiconother: {
        // marginLeft: 150,
        marginLeft: responsiveScreenWidth(46),
    },
    viewlocation: {
        // width: 250,
        // height: 45,
        // padding: 10,
        width: responsiveScreenWidth(68),
        height: responsiveScreenHeight(5.5),
        padding: responsiveScreenHeight(1),
        backgroundColor: Color.MainBlack,
        borderRadius: 20,
        elevation: 5,
        alignSelf: 'center',
        // marginTop: 5,
    },
    textlocation: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
        textAlign: 'center',
        top: responsiveScreenHeight(0.3),
    },
    viewbody: {
        // width: '100%',
        // height: '100%',
        width: responsiveScreenWidth(100),
        height: responsiveScreenHeight(45),
        backgroundColor: Color.MainWhite,
        // bottom: 40,
        bottom: responsiveScreenHeight(5.5),
        borderTopLeftRadius: 38,
        borderTopRightRadius: 38,
    },
    lineShort: {
        // width: 50,
        // height: 4,
        width: responsiveScreenWidth(15),
        height: responsiveScreenHeight(0.5),
        backgroundColor: Color.MainGray3,
        alignSelf: 'center',
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1),
        borderRadius: 10,
    },
    lineShort2: {
        // width: 350,
        // height: 1,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(0.1),
        backgroundColor: Color.MainGray3,
        alignSelf: 'center',
        // marginTop: 15,
        marginTop: responsiveScreenHeight(1.8),
    },
    titlebody: {
        alignSelf: 'center',
        // marginTop: 15,
        marginTop: responsiveScreenHeight(1.8),
        justifyContent: 'center',
    },
    texttitlebody: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewinput: {
        // marginLeft: 20,
        // marginTop: 20,
        marginLeft: responsiveScreenWidth(5.5),
        marginTop: responsiveScreenHeight(2),
    },
    textinput: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
    },
    viewinput2: {
        // width: 360,
        // height: 40,
        width: responsiveScreenWidth(88),
        height: responsiveScreenHeight(4.8),
        backgroundColor: Color.BackGround,
        borderRadius: 12,
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1.2),
    },
    viewinput3: {
        // width: 360,
        // height: 40,
        width: responsiveScreenWidth(88),
        height: responsiveScreenHeight(4.8),
        backgroundColor: Color.BackGround,
        borderRadius: 12,
        // marginTop: 10,
        marginTop: responsiveScreenHeight(1.2),
        flexDirection: 'row',
    },
    textinputview: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: 'bold',
        letterSpacing: 0.25,
        // marginLeft: 10,
        left: responsiveScreenWidth(2),
    },
    textinputview2: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.7),
        fontWeight: 'bold',
        letterSpacing: 0.25,
        // marginLeft: 10,
        left: responsiveScreenWidth(2),
        // width: '90%',
        // top: 1,
        width: responsiveScreenWidth(81.5),
        top: responsiveScreenHeight(0.1),
    },
    textShowinputview: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.6),
        fontWeight: 'bold',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // marginLeft: 10,
        // width: '90%',
        left: responsiveScreenWidth(2),
        width: responsiveScreenWidth(81.5),
    },
    iconaddress: {
        // marginTop: 8,
        top: responsiveScreenHeight(1.1),
        justifyContent: 'flex-end',
        // right: 10,
        right: responsiveScreenWidth(2),
    },
    checkbox: {
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        // marginTop: 15,
        marginTop: responsiveScreenHeight(1.8),
    },
    textcheckbox: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.Black,
        letterSpacing: 0.25,
    },
});

export default StyleAddNewress;