import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenWidth, responsiveScreenFontSize, responsiveScreenHeight } from "react-native-responsive-dimensions";

const StyleShippingAddress = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.WhiteLey,
    },
    header: {
        // marginTop: 25,
        marginTop: responsiveScreenHeight(2),
    },
    headerbar: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 15,
        // marginTop: 2,
        marginLeft: responsiveScreenWidth(2),
        marginTop: responsiveScreenHeight(0.5),
    },
    title: {
        // fontSize: 20,
        fontSize: responsiveScreenFontSize(2.4),
        fontWeight: 'bold',
        // marginLeft: 10,
        left: responsiveScreenWidth(3),
        color: Color.MainBlack,
    },
    viewapply: {
        justifyContent: 'center',
        alignItems: 'center',
        // width: '100%',
        marginTop: 'auto',
        // height: 95,
        height: responsiveScreenHeight(12),
        backgroundColor: Color.MainWhite,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderTopWidth: 1,
        borderColor: Color.Black,
    },
    apply: {
        // width: 320,
        // height: 50,
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(6),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
    },
    textapply: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    viewaddress: {
        // marginTop: 20,
        // marginBottom: 10,
        marginTop: responsiveScreenHeight(2),
        marginBottom: responsiveScreenHeight(1),
    },
    viewitemaddress: {
        flexDirection: 'row',
        alignItems: 'center',
        // marginTop: 10,
        // width: '96%',
        // height: 80,
        width: responsiveScreenWidth(95),
        height: responsiveScreenHeight(7.8),
        top: responsiveScreenHeight(0.5),
        backgroundColor: Color.MainWhite,
        borderRadius: 15,
        elevation: 5,
        alignSelf: 'center',
        // marginBottom: 20,
        marginBottom: responsiveScreenHeight(2),
    },
    viewimage: {
        // width: 50,
        // height: 50,
        width: responsiveScreenWidth(11.8),
        height: responsiveScreenHeight(5.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(2),
    },
    backgroundimage: {
        position: 'absolute',
        // width: 30,
        // height: 30,
        width: responsiveScreenWidth(7.1),
        height: responsiveScreenHeight(3.3),
        borderRadius: 25,
        backgroundColor: Color.MainWhite,
    },
    imageaddress: {
        // width: 35,
        // height: 35,
        width: responsiveScreenWidth(8.8),
        height: responsiveScreenHeight(4),
    },
    viewitem: {
        // marginLeft: 10,
        marginLeft: responsiveScreenWidth(2),
        flexDirection: 'column',
        // gap: 5,
        gap: responsiveScreenHeight(0.5),
    },
    textname: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.9),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    textaddress: {
        // fontSize: 14,
        fontSize: responsiveScreenFontSize(1.8),
        color: Color.MainGray2,
        fontWeight: 'bold',
        // width: 260,
        width: responsiveScreenWidth(66),
    },
    viewdefault: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 5,
        gap: responsiveScreenHeight(0.8),
    },
    textdefault: {
        // fontSize: 13.2,
        fontSize: responsiveScreenFontSize(1.6),
        color: Color.MainBlack,
        fontWeight: '600',
        // width: 60,
        // height: 20,
        width: responsiveScreenWidth(15),
        height: responsiveScreenHeight(2.3),
        backgroundColor: Color.MainGray3,
        borderRadius: 5,
        textAlign: 'center',
    },
    viewcheckbox: {
        flexDirection: 'row',
        alignItems: 'center',
        // gap: 5,
        gap: responsiveScreenHeight(0.8),
    },
    checkbox: {
        // right: 10,
        right: responsiveScreenWidth(2),
    },
    viewadd: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    add: {
        // width: 320,
        // height: 50,
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(5.5),
        backgroundColor: Color.MainGray3,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textadd: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '600',
        color: Color.MainBlack,
    },
});



export default StyleShippingAddress;