import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

const StyleEditProfile = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    viewbody: {
        backgroundColor: Color.MainWhite,
        // marginTop: 30,
        // gap: 20,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(2),
    },
    viewheader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 8,
        // top: 1,
        marginLeft: responsiveScreenWidth(2),
        color: Color.Black,
    },
    textheader: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.1),
        fontWeight: 'bold',
        // marginLeft: 14,
        left: responsiveScreenWidth(4),
        color: Color.MainBlack,
    },
    containerInput: {
        // gap: 6,
        // bottom: 8,
        gap: responsiveScreenHeight(0.8),
        bottom: responsiveScreenHeight(0.9),
    },
    viewphone: {
        marginTop: responsiveScreenHeight(2),
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(6.3),
        backgroundColor: Color.BackGround,
        borderRadius: 17,
        alignSelf: 'center',
    },
    textphone: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.MainBlack,
        letterSpacing: 0.5,
        fontWeight: '600',
        // height: 55,
        height: responsiveScreenHeight(6),
        borderRadius: 17,
    },
    viewinput: {
        // marginTop: 20,
        // marginLeft: 20,
        marginTop: responsiveScreenHeight(2),
        marginLeft: responsiveScreenWidth(5.5),
        // width: '90%',
        // height: 60,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(6.8),
        backgroundColor: Color.BackGround,
        borderRadius: 14,
    },
    textname: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.6),
        color: Color.MainRed,
        // marginLeft: 18,
        // marginTop: 5,
        marginTop: responsiveScreenHeight(0.5),
        marginLeft: responsiveScreenWidth(4),
        letterSpacing: 0.5,
        fontWeight: '600',
    },
    textmail: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        color: Color.MainBlack,
        // marginLeft: 18,
        left: responsiveScreenWidth(3.8),
        fontWeight: '500',
        // marginTop: 8,
        top: responsiveScreenHeight(1),
    },
    viewinfor: {
        flexDirection: 'row',
    },
    iconcalendar: {
        color: Color.MainBlack,
        // marginLeft: 215,
        left: responsiveScreenWidth(60),
        top: responsiveScreenHeight(1),
    },
    iconemail: {
        color: Color.MainBlack,
        // top: 8,
        top: responsiveScreenHeight(0.9),
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveScreenWidth(4.8),
    },
    textinput: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        color: Color.MainBlack,
        // marginLeft: 14,
        left: responsiveScreenWidth(3.1),
        fontWeight: '500',
        bottom: 4,
    },
    selectedDateText: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        color: Color.MainBlack,
        // marginLeft: 18,
        left: responsiveScreenWidth(3.1),
        fontWeight: '500',
        // marginVertical: 12,
        marginVertical: responsiveScreenHeight(1.5),
    },
    button: {
        // marginTop: 18,
        // width: 300,
        // height: 50,
        marginTop: responsiveScreenHeight(5.8),
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(6),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        elevation: 5,
    },
    textbutton: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    textclose: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    placeholderStyle: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        fontWeight: '500',
        // marginLeft: 18,
        left: responsiveScreenWidth(4.2),
    },
    selectedTextStyle: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.85),
        fontWeight: '500',
        // marginLeft: 18,
        left: responsiveScreenWidth(4.2),
        letterSpacing: 0.5,
    },
    inputSearchStyle: {

    },
    iconStyle: {
        // marginRight: 14,
        // width: 25,
        // height: 25,
        right: responsiveScreenWidth(4),
        width: responsiveScreenWidth(4),
        height: responsiveScreenHeight(2.8),
        tintColor: Color.MainBlack,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        // padding: 20,
        // borderRadius: 8,
        // width: 300,
        // height: 142,
        borderRadius: 8,
        width: responsiveScreenWidth(76),
        height: responsiveScreenHeight(16),
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewtitleModal: {
        top: responsiveScreenHeight(1.8),
    },
    modalTitle: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(1.9),
        fontFamily: 'Roboto-Bold',
        // marginBottom: 3,
        marginBottom: responsiveScreenHeight(0.3),
        textAlign: 'center',
        color: Color.MainBlack,
    },
    modalText: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(1.8),
        // marginBottom: 10,
        // width: 280,
        marginBottom: responsiveScreenHeight(1.2),
        width: responsiveScreenWidth(76),
        textAlign: 'center',
        color: Color.MainBlack,
        fontWeight: '500',
    },
    line: {
        // width: '115%',
        width: responsiveScreenWidth(76),
        height: 1,
        backgroundColor: Color.MainGray3,
        alignSelf: 'center',
        marginTop: responsiveScreenHeight(2.8),
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'center',
        // gap: 15,
        gap: responsiveScreenWidth(4),
        alignItems: 'center',
    },
    linebutton: {
        // width: 1,
        // height: 42,
        width: responsiveScreenWidth(0.2),
        height: responsiveScreenHeight(4.5),
        backgroundColor: Color.MainGray3,
        // left: 10,
        left: responsiveScreenWidth(2),
    },
    modalButtonTextBack: {
        color: Color.MainBlue,
        // fontSize: 16,
        // right: 15,
        fontSize: responsiveScreenFontSize(1.9),
        right: responsiveScreenWidth(6),
    },
    modalButtonTextSave: {
        color: Color.MainBlue,
        // fontSize: 16,
        // left: 25,
        fontSize: responsiveScreenFontSize(1.9),
        left: responsiveScreenWidth(8),
    },
});


export default StyleEditProfile;