import { StyleSheet } from "react-native";
import { Color } from "../../../config/Color";
import { responsiveScreenFontSize, responsiveScreenWidth, responsiveScreenHeight } from "react-native-responsive-dimensions";

const styleFillProfile = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.MainWhite,
    },
    viewbody: {
        backgroundColor: Color.MainWhite,
        // marginTop: 30,
        // gap: 20,
        marginTop: responsiveScreenHeight(2),
        gap: responsiveScreenHeight(2),
    },
    viewheader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconback: {
        // marginLeft: 8,
        // top: 1,
        marginLeft: responsiveScreenWidth(1.5),
        color: Color.Black,
    },
    textheader: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        // marginLeft: 14,
        left: responsiveScreenWidth(2),
        color: Color.MainBlack,
    },
    viewimage: {
        alignItems: 'center',
        // bottom: 5,
        // right: 5,
        // top: 5,
        bottom: responsiveScreenHeight(0.5),
        right: responsiveScreenWidth(0.5),
        top: responsiveScreenHeight(0.5),
    },
    viewbuttonimage: {
        alignItems: 'center',
        flexDirection: 'row',
        // marginLeft: 14,
        left: responsiveScreenWidth(5),
    },
    image: {
        // width: 120,
        // height: 120,
        width: responsiveScreenWidth(30),
        height: responsiveScreenWidth(30),
        borderRadius: 65,
        // marginLeft: 22,
    },
    iconimage: {
        color: Color.MainBlack,
        // marginTop: 88,
        top: responsiveScreenHeight(5),
        // right: 32,
        right: responsiveScreenWidth(8),
    },
    imagelogo: {
        // width: 32,
        // height: 32,
        width: responsiveScreenWidth(8),
        height: responsiveScreenWidth(8),
    },
    containerInput: {
        // gap: 6,
        gap: responsiveScreenHeight(0.5),
    },
    viewphone: {
        // marginTop: 20,
        // width: '90%',
        // height: 55,
        marginTop: responsiveScreenHeight(2),
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(6.5),
        backgroundColor: Color.BackGround,
        borderRadius: 17,
        alignSelf: 'center',
    },
    textphone: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(2),
        color: Color.MainBlack,
        letterSpacing: 0.5,
        fontWeight: '600',
        // height: 55,
        height: responsiveScreenHeight(6),
        borderRadius: 17,
    },
    viewinput: {
        // marginTop: 20,
        // marginLeft: 20,
        marginTop: responsiveScreenHeight(1.5),
        marginLeft: responsiveScreenWidth(5),
        // width: '90%',
        // height: 60,
        width: responsiveScreenWidth(90),
        height: responsiveScreenHeight(6.5),
        backgroundColor: Color.BackGround,
        borderRadius: 14,
    },
    textname: {
        // fontSize: 13,
        fontSize: responsiveScreenFontSize(1.7),
        color: Color.MainRed,
        // marginLeft: 18,
        // marginTop: 5,
        marginTop: responsiveScreenHeight(0.5),
        left: responsiveScreenWidth(3.5),
        letterSpacing: 0.5,
        fontWeight: '600',
    },
    textmail: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.9),
        color: Color.MainBlack,
        // marginLeft: 18,
        left: responsiveScreenWidth(3.5),
        fontWeight: '500',
        top: responsiveScreenHeight(0.8),
    },
    viewinfor: {
        flexDirection: 'row',
    },
    iconcalendar: {
        color: Color.MainBlack,
        // marginLeft: 160,
        // top: 5,
        left: responsiveScreenWidth(60),
        top: responsiveScreenHeight(0.5),
    },
    iconemail: {
        color: Color.MainBlack,
        top: 3,
        marginLeft: 'auto',
        // marginRight: 15,
        right: responsiveScreenWidth(3.8),
    },
    textinput: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.95),
        color: Color.MainBlack,
        // marginLeft: 14,
        left: responsiveScreenWidth(2.6),
        fontWeight: '500',
        // bottom: 4,
        // bottom: 11,
        bottom: responsiveScreenHeight(0.8),
    },
    selectedDateText: {
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.95),
        color: Color.MainBlack,
        // marginLeft: 18,
        left: responsiveScreenWidth(3.5),
        fontWeight: '500',
        // marginVertical: 12,
        marginVertical: responsiveScreenHeight(1.5),
    },
    button: {
        // marginTop: 18,
        // width: 300,
        // height: 50,
        marginTop: responsiveScreenHeight(2),
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(6.5),
        marginBottom: responsiveScreenHeight(2),
        backgroundColor: Color.MainBlack,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        elevation: 5,
    },
    textbutton: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainWhite,
    },
    textclose: {
        // fontSize: 18,
        fontSize: responsiveScreenFontSize(2.3),
        fontWeight: 'bold',
        color: Color.MainBlack,
    },
    selectcontry: {
        // width: 300,
        // height: 50,
        width: responsiveScreenWidth(80),
        height: responsiveScreenHeight(6.5),
        backgroundColor: Color.BackGround,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        elevation: 5,
    },
    placeholderStyle: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.95),
        fontWeight: '500',
        // marginLeft: 18,
        left: responsiveScreenWidth(3.5),
    },
    selectedTextStyle: {
        color: Color.MainBlack,
        // fontSize: 15,
        fontSize: responsiveScreenFontSize(1.95),
        fontWeight: '500',
        // marginLeft: 18,
        letterSpacing: 0.5,
        left: responsiveScreenWidth(3.5),
    },
    iconStyle: {
        // marginRight: 14,
        // width: 25,
        // height: 25,
        marginRight: responsiveScreenWidth(3.5),
        width: responsiveScreenWidth(6),
        height: responsiveScreenWidth(6),
        tintColor: Color.MainBlack,
    },
    viewmodal: {
        backgroundColor: Color.MainWhite,
        width: responsiveScreenWidth(52),
        height: responsiveScreenHeight(30),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        // marginTop: '70%',
        marginTop: responsiveScreenHeight(25),
        elevation: 6,
        // gap: 20,
        gap: responsiveScreenHeight(2),
    },
    texttitle: {
        // fontSize: 17,
        fontSize: responsiveScreenFontSize(2.2),
        fontWeight: '600',
        color: Color.MainBlack,
        letterSpacing: 0.25,
        // bottom: 10,
        bottom: responsiveScreenHeight(1),
    },
    viewmodalcontainer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        // gap: 20,
        gap: responsiveScreenHeight(2),
    },
    viewcancel: {
        // width: 135,
        // height: 40,
        width: responsiveScreenWidth(35),
        height: responsiveScreenHeight(4),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Color.MainGray3,
        elevation: 5,
    },
    textcancel: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainBlack,
    },
    viewlogout: {
        // width: 135,
        // height: 40,
        width: responsiveScreenWidth(35),
        height: responsiveScreenHeight(4),
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Color.MainBlack,
        elevation: 5,
    },
    textlogout: {
        // fontSize: 16,
        fontSize: responsiveScreenFontSize(2),
        fontWeight: '500',
        color: Color.MainWhite,
    },
});


export default styleFillProfile;